// Package builtin implements engine-internal pipeline actions.
//
// A builtin is an action described in a pipeline YAML step as:
//
//   - name: some-step
//     type: builtin
//     cmd: <name>
//     with:
//     key: value
//
// Unlike type: shell, type: command (registry), and type: devbox (CLI), a builtin is
// executed directly in Go — no subprocess is spawned. This makes destructive
// and file-system operations safe, auditable, and visible in plan output.
//
// Canonical builtins:
//   - confirm                       — interactive user confirmation prompt
//   - message                       — output styled text
//   - service_configs_copy          — copy service template configs into the hub
//   - service_configs_check         — verify service config files exist
//   - service_dirs_ensure           — ensure service hub directories exist
//   - docker_remove_project_volumes — remove all Docker volumes for the project
//   - docker_wait_healthy           — wait until containers are healthy
//   - containers_running            — fast "is running" check (no polling, no timeout)
//   - docker_daemon_start           — start a named daemon container (docker compose run -d)
//   - docker_daemon_logs            — tail daemon container logs foreground (interactive)
//   - docker_daemon_stop            — stop a named daemon container (idempotent)
//   - daemons_reap                  — stop all project daemon containers; auto-injected as _auto_reap_daemons
//   - remove_paths                  — delete declared paths inside the project root
package builtin

import (
	"context"
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"devbox-cli/internal/config"
	"devbox-cli/internal/render"
)

// ExecContext holds the runtime context passed to every builtin execution.
type ExecContext struct {
	// Config is the merged devbox configuration.
	Config *config.DevboxConfig
	// DockerConfig is the resolved docker policy. Callers must pre-normalise
	// missing-file (os.ErrNotExist) to &config.DockerConfig{} so builtins can
	// pass it directly to docker.NewCompose without nil-checks.
	DockerConfig *config.DockerConfig
	// ProjectRoot is the absolute path to the project root (directory of devbox.yml).
	ProjectRoot string
	// Output is the render writer for styled terminal output. All builtin
	// output flows through this single channel — the executor wires it to
	// the per-step lineTee so frames reach Reporter.StepOutput like every
	// other child line.
	Output *render.Writer
	// Stdin is the reader used for interactive prompts. Defaults to os.Stdin when nil.
	Stdin io.Reader
	// SkipConfirm suppresses all confirm builtins (e.g. when --yes is passed).
	SkipConfirm bool
	// ConfirmFunc is an optional callback for interactive confirmation.
	// When non-nil, the confirm builtin uses it instead of reading from stdin.
	// Returns (true, nil) if confirmed, (false, nil) if denied.
	ConfirmFunc func(msg, okMsg, stopMsg string) (bool, error)
}

// Builtin is an engine-internal pipeline action.
type Builtin interface {
	// Validate checks that the with parameters are valid before the pipeline runs.
	Validate(with map[string]any) error
	// Describe returns a short human-readable description used in plan output.
	Describe(with map[string]any) string
	// Run executes the builtin action. ctx propagates cancellation; long-running
	// loops (e.g. health polling) should select on ctx.Done() to abort promptly.
	Run(ctx context.Context, with map[string]any, ectx ExecContext) error
}

// Kind classifies how a builtin may be invoked.
type Kind int

const (
	// KindAction builtins are user-callable step actions (confirm, message, service_configs_copy, etc.).
	// They run in the body of a deploy/lifecycle step authored in YAML.
	KindAction Kind = iota
	// KindPredicate builtins are read-only checks used in check: positions and validate.yml cmd: entries.
	// They MUST NOT have side effects (no volume removal, no container starts).
	KindPredicate
	// KindInternal builtins are engine-only; they cannot be invoked from user-authored YAML.
	// They are injected by the engine itself (e.g. daemons_reap in the synthetic _auto_reap_daemons phase,
	// or docker_daemon_start/stop/logs generated by daemon command expansion).
	KindInternal
)

// CallerContext identifies who is invoking a builtin, used for kind/context gating.
type CallerContext int

const (
	// CtxUserYAML is used when a builtin is invoked from user-authored YAML (deploy.yml step body,
	// commands.yml type: builtin). Only KindAction builtins are allowed here.
	CtxUserYAML CallerContext = iota
	// CtxPredicate is used when a builtin is invoked from a check: position in a pipeline step
	// or from a validate.yml cmd: entry. KindAction and KindPredicate builtins are both allowed here.
	CtxPredicate
	// CtxInternal is used when a builtin is invoked by the engine itself (engine-synthetic phases
	// or daemon-generated virtual commands). Only KindInternal builtins are allowed here.
	CtxInternal
)

// registryEntry pairs a Builtin implementation with its kind metadata.
type registryEntry struct {
	impl Builtin
	kind Kind
}

var registry = map[string]registryEntry{
	// KindAction: user-callable step actions with side effects
	"confirm":                       {confirmBuiltin{}, KindAction},
	"message":                       {messageBuiltin{}, KindAction},
	"service_configs_copy":          {serviceConfigsCopyBuiltin{}, KindAction},
	"service_configs_check":         {serviceConfigsCheckBuiltin{}, KindAction},
	"service_dirs_ensure":           {serviceDirsEnsureBuiltin{}, KindAction},
	"docker_remove_project_volumes": {dockerRemoveProjectVolumesBuiltin{}, KindAction},
	"docker_wait_healthy":           {dockerWaitHealthyBuiltin{}, KindAction},
	"remove_paths":                  {removePathsBuiltin{}, KindAction},
	// KindPredicate: read-only checks for check: positions and validate.yml
	"containers_running": {containersRunningBuiltin{}, KindPredicate},
	"shell":              {shellBuiltin{}, KindPredicate},
	"file_exists":        {fileExistsBuiltin{}, KindPredicate},
	"executable_in_path": {executableInPathBuiltin{}, KindPredicate},
	"env_keys_present":   {envKeysPresentBuiltin{}, KindPredicate},
	"tcp_reachable":      {tcpReachableBuiltin{}, KindPredicate},
	// KindInternal: engine-only; not callable from user-authored YAML
	"docker_daemon_start": {daemonStartBuiltin{}, KindInternal},
	"docker_daemon_logs":  {daemonLogsBuiltin{}, KindInternal},
	"docker_daemon_stop":  {daemonStopBuiltin{}, KindInternal},
	"daemons_reap":        {daemonsReapBuiltin{}, KindInternal},
}

// Get returns the named builtin if it exists and is compatible with ctx.
// Returns (nil, false) when the name is unknown or when the builtin's kind
// is not compatible with the caller context.
func Get(name string, ctx CallerContext) (Builtin, bool) {
	entry, ok := registry[name]
	if !ok {
		return nil, false
	}
	if !kindAllowed(entry.kind, ctx) {
		return nil, false
	}
	return entry.impl, true
}

// kindAllowed reports whether a builtin of the given kind may be invoked from ctx.
//
// Rules:
//   - KindAction: allowed in CtxUserYAML (step body) and CtxPredicate (check: position).
//     Actions may be read-only (e.g. service_configs_check) and are safe in check: position.
//   - KindPredicate: only in CtxPredicate. These builtins have boolean exit-code semantics
//     and MUST NOT appear in step bodies — they don't produce side-effect output.
//   - KindInternal: only in CtxInternal (engine-synthetic phases or daemon-generated commands).
func kindAllowed(k Kind, ctx CallerContext) bool {
	switch k {
	case KindAction:
		return ctx == CtxUserYAML || ctx == CtxPredicate
	case KindPredicate:
		return ctx == CtxPredicate
	case KindInternal:
		return ctx == CtxInternal
	}
	return false
}

// kindMismatchHint returns a human-readable hint when a builtin's kind is
// incompatible with the given caller context.
func kindMismatchHint(name string, k Kind, _ CallerContext) string {
	switch k {
	case KindInternal:
		return fmt.Sprintf("builtin %q is engine-internal and cannot be called from user-authored YAML; it is invoked automatically by the engine", name)
	case KindPredicate:
		return fmt.Sprintf("builtin %q is a predicate and can only be used in check: positions or validate.yml cmd: entries, not as a step body action", name)
	case KindAction:
		return fmt.Sprintf("builtin %q is an action and cannot be called from this context", name)
	}
	return fmt.Sprintf("builtin %q cannot be invoked from this context", name)
}

// interactiveBuiltins is the single source of truth for which builtins require
// interactive terminal access at runtime. Both the pipeline plan-time guard and
// the workflow runtime dispatch consult this set to reject these builtins
// inside parallel groups.
var interactiveBuiltins = map[string]bool{
	"confirm":            true,
	"docker_daemon_logs": true,
}

// IsInteractive reports whether the named builtin requires interactive
// terminal access (stdin or a foreground TTY) and therefore cannot run inside
// a parallel group. Future interactive builtins register here.
func IsInteractive(name string) bool {
	return interactiveBuiltins[name]
}

// Validate checks that name is a known builtin compatible with ctx and that with params are valid.
func Validate(name string, with map[string]any, ctx CallerContext) error {
	entry, ok := registry[name]
	if !ok {
		known := knownNames()
		return fmt.Errorf("unknown builtin %q (known: %s)", name, strings.Join(known, ", "))
	}
	if !kindAllowed(entry.kind, ctx) {
		return fmt.Errorf("%s", kindMismatchHint(name, entry.kind, ctx))
	}
	return entry.impl.Validate(with)
}

// Describe returns a human-readable description for plan display.
// Unlike Get/Validate/Run, Describe is display-only and does not enforce kind/context gating.
func Describe(name string, with map[string]any) string {
	entry, ok := registry[name]
	if !ok {
		return fmt.Sprintf("builtin: %s", name)
	}
	return entry.impl.Describe(with)
}

// Run executes the named builtin with the given parameters and context.
// ctx propagates cancellation to long-running builtins.
// callerCtx enforces kind/context compatibility before execution.
func Run(ctx context.Context, name string, with map[string]any, ectx ExecContext, callerCtx CallerContext) error {
	entry, ok := registry[name]
	if !ok {
		return fmt.Errorf("unknown builtin %q", name)
	}
	if !kindAllowed(entry.kind, callerCtx) {
		return fmt.Errorf("%s", kindMismatchHint(name, entry.kind, callerCtx))
	}
	return entry.impl.Run(ctx, with, ectx)
}

func knownNames() []string {
	names := make([]string, 0, len(registry))
	for name := range registry {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// getStringParam returns the string value of key from with, or defaultVal if absent/nil.
func getStringParam(with map[string]any, key, defaultVal string) string {
	if with == nil {
		return defaultVal
	}
	v, ok := with[key]
	if !ok || v == nil {
		return defaultVal
	}
	return fmt.Sprintf("%v", v)
}

// getStringSlice returns a string slice from with[key].
// Accepts []any, []string, or a single string value.
func getStringSlice(with map[string]any, key string) ([]string, error) {
	if with == nil {
		return nil, nil
	}
	v, ok := with[key]
	if !ok || v == nil {
		return nil, nil
	}
	switch val := v.(type) {
	case []any:
		result := make([]string, 0, len(val))
		for _, item := range val {
			result = append(result, fmt.Sprintf("%v", item))
		}
		return result, nil
	case []string:
		return val, nil
	case string:
		if val == "" {
			return nil, nil
		}
		return []string{val}, nil
	default:
		return nil, fmt.Errorf("param %q: expected string or list, got %T", key, v)
	}
}

// getBoolParam returns the boolean value of key from with, or defaultVal if
// absent/nil. Accepts bool or string ("true"/"false") values.
func getBoolParam(with map[string]any, key string, defaultVal bool) bool {
	if with == nil {
		return defaultVal
	}
	v, ok := with[key]
	if !ok || v == nil {
		return defaultVal
	}
	switch val := v.(type) {
	case bool:
		return val
	case string:
		switch strings.ToLower(strings.TrimSpace(val)) {
		case "true", "yes", "1":
			return true
		case "false", "no", "0", "":
			return false
		}
	}
	return defaultVal
}

// getStringMap returns a string map from with[key], rendering values via
// fmt.Sprint when they are not already strings. Returns nil when key absent.
func getStringMap(with map[string]any, key string) (map[string]string, error) {
	if with == nil {
		return nil, nil
	}
	v, ok := with[key]
	if !ok || v == nil {
		return nil, nil
	}
	m, ok := v.(map[string]any)
	if !ok {
		if ms, ok := v.(map[string]string); ok {
			return ms, nil
		}
		return nil, fmt.Errorf("param %q: expected map, got %T", key, v)
	}
	out := make(map[string]string, len(m))
	for k, val := range m {
		out[k] = fmt.Sprint(val)
	}
	return out, nil
}

// getMapAny returns a map[string]any from with[key]. Returns nil when absent.
func getMapAny(with map[string]any, key string) (map[string]any, error) {
	if with == nil {
		return nil, nil
	}
	v, ok := with[key]
	if !ok || v == nil {
		return nil, nil
	}
	m, ok := v.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("param %q: expected map, got %T", key, v)
	}
	return m, nil
}

// sortedKeys returns the sorted keys of a string map for deterministic iteration.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// getDurationParam returns the time.Duration value of key from with, or defaultVal if absent/nil.
// Accepts string values parseable by time.ParseDuration.
func getDurationParam(with map[string]any, key string, defaultVal time.Duration) (time.Duration, error) {
	s := getStringParam(with, key, "")
	if s == "" {
		return defaultVal, nil
	}
	d, err := time.ParseDuration(s)
	if err != nil {
		return 0, fmt.Errorf("param %q: invalid duration %q: %w", key, s, err)
	}
	return d, nil
}
