// Code generated by scripts/gen-docs-content-hashes.sh; DO NOT EDIT.

package docs

// ContentHashes maps relative file paths to their content SHA256 hashes (first 12 hex chars).
// Generated from docs/reference and docs/internals at build time.
// See docs/reference/docs/index.md for details on the hash-based staleness check.
var ContentHashes = map[string]string{}
