package envfile

import (
	"fmt"
	"strings"

	"github.com/semsemyonoff/dwe/internal/core/project/config"
	"github.com/semsemyonoff/dwe/internal/shared/hostid"
)

// HostUID returns the UID to use for container builds.
// On macOS, Docker Desktop runs containers in a Linux VM where host UIDs don't
// map directly, so 1000 is the conventional user UID inside the image.
// On Linux, the actual host UID is used so file permissions match.
func HostUID() string { return hostid.UID() }

// HostGID returns the GID to use for container builds (same platform logic as HostUID).
func HostGID() string { return hostid.GID() }

// BuildContent renders the .env content from the export spec.
//
// System variables (always emitted, not part of the export spec):
//   - PROJECT — project.name
//   - UID     — host UID for container builds (1000 on macOS, actual on Linux)
//   - GID     — host GID for container builds (1000 on macOS, actual on Linux)
//
// The names of these variables are reserved (see config.ReservedExportNames):
// LoadConfig rejects any export rule that tries to redeclare them, and this
// function defensively skips such rules in case it is called with a config
// that bypassed validation.
func BuildContent(cfg *config.DweConfig) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by dwe — do not edit manually\n\n")

	// System variables: always emitted regardless of export spec.
	systemValues := map[string]string{
		"PROJECT": cfg.Project.Name,
		"UID":     HostUID(),
		"GID":     HostGID(),
	}
	for _, name := range config.ReservedExportNames {
		fmt.Fprintf(&b, "%s=%s\n", name, systemValues[name])
	}

	for _, rule := range cfg.Exports.Env {
		// Defense-in-depth: if a caller built a config without LoadConfig,
		// silently drop reserved-name rules rather than producing duplicates.
		if config.IsReservedExportName(rule.Name) {
			continue
		}
		// Evaluate when condition: skip rule if the path resolves to a falsy value.
		if rule.When != "" {
			v, _ := config.ResolvePath(cfg.Raw, rule.When)
			if !IsTruthy(v) {
				continue
			}
		}

		// Resolve value from the effective config.
		// For typed formats (bool, int), always use the resolved value even when
		// falsy (false, 0) so that TOOL_FOO=false and PORT=0 are emitted correctly.
		// For string format, an empty resolved value falls back to default.
		value := rule.Default
		if v, ok := config.ResolvePath(cfg.Raw, rule.From); ok {
			if rule.Format == "bool" || rule.Format == "int" || IsTruthy(v) {
				value = FormatValue(v, rule.Format)
			}
		} else if rule.Required && value == "" {
			return "", fmt.Errorf("export %q: required path %q not found in config", rule.Name, rule.From)
		}

		if rule.Comment != "" {
			fmt.Fprintf(&b, "# %s\n", rule.Comment)
		}
		fmt.Fprintf(&b, "%s=%s\n", rule.Name, value)
	}

	return b.String(), nil
}

// IsTruthy returns whether v represents a truthy config value.
// nil, false, 0, "", "false", "0" are all falsy.
func IsTruthy(v any) bool {
	if v == nil {
		return false
	}
	switch val := v.(type) {
	case bool:
		return val
	case int:
		return val != 0
	case float64:
		return val != 0
	case string:
		return val != "" && val != "false" && val != "0"
	default:
		return true
	}
}

// FormatValue converts a raw config value to a string for .env output.
// The format hint influences how ambiguous types (e.g. bool) are rendered.
func FormatValue(v any, format string) string {
	if format == "bool" {
		if val, ok := v.(bool); ok {
			if val {
				return "true"
			}
			return "false"
		}
	}
	return fmt.Sprintf("%v", v)
}
