package envfile

import (
	"strings"
	"testing"

	"github.com/semsemyonoff/dwe/internal/core/project/config"
)

// makeEnvCfg builds a DweConfig with the given export rules and raw map.
//
// These tests pass an empty baseDir to BuildContent: that skips the docker.yml
// read entirely, so COMPOSE_PROJECT_NAME falls back to the lowercased
// FullName() and no test needs a project tree on disk. The docker.yml /
// docker.local.yml precedence lives in compose_name_test.go.
func makeEnvCfg(rules []config.ExportRule, raw map[string]any) *config.DweConfig {
	return &config.DweConfig{
		Project: config.ProjectConfig{Name: "laravel", Prefix: "dwe"},
		Exports: config.ExportsConfig{Env: rules},
		Raw:     raw,
	}
}

func TestBuildContent_alwaysEmitsProjectAndHeader(t *testing.T) {
	cfg := makeEnvCfg(nil, map[string]any{})
	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "# Generated by dwe") {
		t.Error("missing header comment")
	}
	if !strings.Contains(out, "PROJECT=laravel") {
		t.Error("missing PROJECT system variable")
	}
}

func TestBuildContent_silentlyDropsReservedRules(t *testing.T) {
	// Defense-in-depth: a rule with a reserved name should be silently dropped
	// even if it slips past LoadConfig validation, so the output never has
	// duplicate lines for PROJECT/UID/GID/COMPOSE_PROJECT_NAME.
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "PROJECT", From: "env"},
		{Name: "UID", From: "env"},
		{Name: "GID", From: "env"},
		{Name: "COMPOSE_PROJECT_NAME", From: "env"},
		{Name: "MY_VAR", From: "env"},
	}, map[string]any{"env": "shouldnotappear"})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	for _, name := range config.ReservedExportNames {
		// Count whole lines, not substrings: "PROJECT=" is a substring of
		// "COMPOSE_PROJECT_NAME=".
		if got := countAssignments(out, name); got != 1 {
			t.Errorf("%s should appear exactly once in output, got %d:\n%s", name, got, out)
		}
		if strings.Contains(out, name+"=shouldnotappear") {
			t.Errorf("rule with reserved name %s leaked its From value into the output:\n%s", name, out)
		}
	}
	if !strings.Contains(out, "MY_VAR=shouldnotappear") {
		t.Errorf("non-reserved rule should still be emitted, got:\n%s", out)
	}
}

func TestBuildContent_simpleStringRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MY_VAR", From: "env"},
	}, map[string]any{"env": "staging"})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "MY_VAR=staging") {
		t.Errorf("expected MY_VAR=staging, got:\n%s", out)
	}
}

func TestBuildContent_boolFormatTrue(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "USE_HTTPS", From: "runtime.use_https", Format: "bool"},
	}, map[string]any{
		"runtime": map[string]any{"use_https": true},
	})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "USE_HTTPS=true") {
		t.Errorf("expected USE_HTTPS=true, got:\n%s", out)
	}
}

func TestBuildContent_boolFormatFalse(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "USE_HTTPS", From: "runtime.use_https", Format: "bool"},
	}, map[string]any{
		"runtime": map[string]any{"use_https": false},
	})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "USE_HTTPS=false") {
		t.Errorf("expected USE_HTTPS=false, got:\n%s", out)
	}
}

func TestBuildContent_intFormat(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "APP_PORT", From: "services.app.ports.http", Format: "int"},
	}, map[string]any{
		"services": map[string]any{
			"app": map[string]any{
				"ports": map[string]any{"http": 8080},
			},
		},
	})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "APP_PORT=8080") {
		t.Errorf("expected APP_PORT=8080, got:\n%s", out)
	}
}

func TestBuildContent_defaultFallback(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MISSING_VAR", From: "no.such.path", Default: "fallback"},
	}, map[string]any{})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "MISSING_VAR=fallback") {
		t.Errorf("expected MISSING_VAR=fallback, got:\n%s", out)
	}
}

func TestBuildContent_requiredMissingReturnsError(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "REQUIRED_VAR", From: "no.such.path", Required: true},
	}, map[string]any{})

	_, err := BuildContent(cfg, "")
	if err == nil {
		t.Error("expected error for required missing path, got nil")
	}
	if err != nil && !strings.Contains(err.Error(), "required") {
		t.Errorf("expected 'required' in error, got: %v", err)
	}
}

func TestBuildContent_whenFalsySkipsRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "TOOL_ADMINER", From: "tools.adminer.enabled", When: "tools.adminer.enabled", Format: "bool"},
	}, map[string]any{
		"tools": map[string]any{
			"adminer": map[string]any{"enabled": false},
		},
	})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(out, "TOOL_ADMINER") {
		t.Errorf("expected TOOL_ADMINER to be skipped when when-condition is falsy, got:\n%s", out)
	}
}

func TestBuildContent_whenTruthyIncludesRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "TOOL_ADMINER", From: "tools.adminer.enabled", When: "tools.adminer.enabled", Format: "bool"},
	}, map[string]any{
		"tools": map[string]any{
			"adminer": map[string]any{"enabled": true},
		},
	})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "TOOL_ADMINER=true") {
		t.Errorf("expected TOOL_ADMINER=true when when-condition is truthy, got:\n%s", out)
	}
}

func TestBuildContent_commentEmitted(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MY_VAR", From: "env", Comment: "Active env"},
	}, map[string]any{"env": "staging"})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "# Active env") {
		t.Errorf("expected comment in output, got:\n%s", out)
	}
}

// --- IsTruthy tests ---

func TestIsTruthy(t *testing.T) {
	cases := []struct {
		v    any
		want bool
	}{
		{nil, false},
		{false, false},
		{true, true},
		{0, false},
		{1, true},
		{"", false},
		{"false", false},
		{"0", false},
		{"true", true},
		{"staging", true},
		{map[string]any{}, true}, // unknown type → truthy
	}
	for _, tc := range cases {
		got := IsTruthy(tc.v)
		if got != tc.want {
			t.Errorf("IsTruthy(%#v) = %v, want %v", tc.v, got, tc.want)
		}
	}
}

// --- FormatValue tests ---

func TestFormatValue_boolTrue(t *testing.T) {
	if got := FormatValue(true, "bool"); got != "true" {
		t.Errorf("FormatValue(true, bool) = %q, want true", got)
	}
}

func TestFormatValue_boolFalse(t *testing.T) {
	if got := FormatValue(false, "bool"); got != "false" {
		t.Errorf("FormatValue(false, bool) = %q, want false", got)
	}
}

func TestFormatValue_intFormat(t *testing.T) {
	if got := FormatValue(8080, "int"); got != "8080" {
		t.Errorf("FormatValue(8080, int) = %q, want 8080", got)
	}
}

func TestFormatValue_stringPassthrough(t *testing.T) {
	if got := FormatValue("hello", ""); got != "hello" {
		t.Errorf("FormatValue(hello, ) = %q, want hello", got)
	}
}

func TestFormatValue_boolFormatNonBoolValue(t *testing.T) {
	// When format is bool but value is not a bool, falls through to Sprintf.
	if got := FormatValue("yes", "bool"); got != "yes" {
		t.Errorf("FormatValue(yes, bool) = %q, want yes", got)
	}
}

// --- Regression tests for data-driven tools (raw dot-path resolution) ---

func TestBuildContent_toolPortResolution(t *testing.T) {
	// Tool ports live under services.<name>.ports.<port-name> in the unified schema.
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "ADMINER_PORT", From: "services.adminer.ports.web", Format: "int"},
	}, map[string]any{
		"services": map[string]any{
			"adminer": map[string]any{
				"ports": map[string]any{"web": 8080},
			},
		},
	})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "ADMINER_PORT=8080") {
		t.Errorf("expected ADMINER_PORT=8080, got:\n%s", out)
	}
}

func TestBuildContent_toolHostResolution(t *testing.T) {
	// Tool hosts live under services.<name>.hosts.<host-name>.
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "ADMINER_HOST", From: "services.adminer.hosts.web"},
	}, map[string]any{
		"services": map[string]any{
			"adminer": map[string]any{
				"hosts": map[string]any{"web": "adminer.localhost"},
			},
		},
	})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "ADMINER_HOST=adminer.localhost") {
		t.Errorf("expected ADMINER_HOST=adminer.localhost, got:\n%s", out)
	}
}

// TestBuildContent_multiPortService exercises a service that declares two
// named ports — proves the loader/raw-injection roundtrip and the export
// rule resolution both handle multi-port maps.
func TestBuildContent_multiPortService(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "APP_HTTP_PORT", From: "services.app.ports.http", Format: "int"},
		{Name: "APP_GRPC_PORT", From: "services.app.ports.grpc", Format: "int"},
	}, map[string]any{
		"services": map[string]any{
			"app": map[string]any{
				"ports": map[string]any{"http": 8080, "grpc": 9090},
			},
		},
	})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	for _, want := range []string{"APP_HTTP_PORT=8080", "APP_GRPC_PORT=9090"} {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q, got:\n%s", want, out)
		}
	}
}

// TestUnresolvedRules covers the one shape that renders NAME= silently against
// every neighbouring shape that does not: a default, required (BuildContent
// fails instead), a falsy when: (no line at all) and a path that resolves.
func TestUnresolvedRules(t *testing.T) {
	raw := map[string]any{
		"services": map[string]any{
			"app": map[string]any{
				"enabled": true,
				"ports":   map[string]any{"http": 8080},
			},
			"off": map[string]any{"enabled": false},
		},
		"vars": map[string]any{"empty": nil},
	}

	tests := []struct {
		name string
		rule config.ExportRule
		want bool // reported as rendering empty
	}{
		{"resolving path", config.ExportRule{Name: "APP_PORT", From: "services.app.ports.http"}, false},
		{"missing path", config.ExportRule{Name: "APP_PORT", From: "services.app.ports.htpp"}, true},
		{"missing path with default", config.ExportRule{Name: "APP_URL", From: "runtime.urls.app", Default: "http://localhost"}, false},
		{"missing path required", config.ExportRule{Name: "TOKEN", From: "vars.tokn", Required: true}, false},
		{"missing path skipped by falsy when", config.ExportRule{Name: "OFF_HOST", From: "services.off.hosts.web", When: "services.off.enabled"}, false},
		{"missing path with truthy when", config.ExportRule{Name: "APP_HOST", From: "services.app.hosts.web", When: "services.app.enabled"}, true},
		{"present key holding nil", config.ExportRule{Name: "EMPTY", From: "vars.empty"}, false},
		// No from: at all renders NAME= on purpose. ResolvePath calls an empty
		// path not-found, so without the guard this would warn `from ""` at an
		// author who never wrote one — and config.exports stays silent here.
		{"no from at all", config.ExportRule{Name: "FLAG"}, false},
		{"no from with comment", config.ExportRule{Name: "FLAG", Comment: "left blank on purpose"}, false},
		{"reserved name", config.ExportRule{Name: "PROJECT", From: "vars.nope"}, false},
		{"missing path with bool format", config.ExportRule{Name: "FLAG", From: "services.app.enabld", Format: "bool"}, true},
		{"missing path with int format", config.ExportRule{Name: "PORT", From: "services.app.ports.htp", Format: "int"}, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := UnresolvedRules(makeEnvCfg([]config.ExportRule{tt.rule}, raw))
			if tt.want {
				if len(got) != 1 || got[0].Name != tt.rule.Name || got[0].From != tt.rule.From {
					t.Fatalf("UnresolvedRules = %+v, want one entry for %s/%s", got, tt.rule.Name, tt.rule.From)
				}
				return
			}
			if len(got) != 0 {
				t.Fatalf("UnresolvedRules = %+v, want none", got)
			}
		})
	}
}

// TestUnresolvedRules_orderAndNilConfig pins source order (the order the empty
// lines appear in .env) and the nil-config guard.
func TestUnresolvedRules_orderAndNilConfig(t *testing.T) {
	if got := UnresolvedRules(nil); got != nil {
		t.Errorf("UnresolvedRules(nil) = %+v, want nil", got)
	}

	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "FIRST", From: "vars.a"},
		{Name: "OK", From: "vars.here"},
		{Name: "SECOND", From: "vars.b"},
	}, map[string]any{"vars": map[string]any{"here": "yes"}})

	got := UnresolvedRules(cfg)
	if len(got) != 2 || got[0].Name != "FIRST" || got[1].Name != "SECOND" {
		t.Fatalf("UnresolvedRules = %+v, want FIRST then SECOND", got)
	}
}

// TestUnresolvedRules_matchesBuildContent ties the report to the rendered
// output: every reported rule must actually appear as a bare NAME= line, and
// no unreported rule may.
func TestUnresolvedRules_matchesBuildContent(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "EMPTY_ONE", From: "vars.typo"},
		{Name: "WITH_DEFAULT", From: "vars.typo", Default: "fallback"},
		{Name: "RESOLVED", From: "vars.here"},
	}, map[string]any{"vars": map[string]any{"here": "yes"}})

	out, err := BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "\nEMPTY_ONE=\n") {
		t.Errorf("expected a bare EMPTY_ONE= line, got:\n%s", out)
	}
	got := UnresolvedRules(cfg)
	if len(got) != 1 || got[0].Name != "EMPTY_ONE" {
		t.Fatalf("UnresolvedRules = %+v, want only EMPTY_ONE", got)
	}
}
