package envfile

import (
	"strings"
	"testing"

	"github.com/semsemyonoff/devbox/internal/core/project/config"
)

// makeEnvCfg builds a DevboxConfig with the given export rules and raw map.
func makeEnvCfg(rules []config.ExportRule, raw map[string]any) *config.DevboxConfig {
	return &config.DevboxConfig{
		Project: config.ProjectConfig{Name: "laravel", Prefix: "devbox"},
		Exports: config.ExportsConfig{Env: rules},
		Raw:     raw,
	}
}

func TestBuildContent_alwaysEmitsProjectAndHeader(t *testing.T) {
	cfg := makeEnvCfg(nil, map[string]any{})
	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "# Generated by devbox") {
		t.Error("missing header comment")
	}
	if !strings.Contains(out, "PROJECT=laravel") {
		t.Error("missing PROJECT system variable")
	}
}

func TestBuildContent_silentlyDropsReservedRules(t *testing.T) {
	// Defense-in-depth: a rule with a reserved name should be silently dropped
	// even if it slips past LoadConfig validation, so the output never has
	// duplicate lines for PROJECT/UID/GID.
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "PROJECT", From: "state"},
		{Name: "UID", From: "state"},
		{Name: "GID", From: "state"},
		{Name: "MY_VAR", From: "state"},
	}, map[string]any{"state": "shouldnotappear"})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	for _, name := range config.ReservedExportNames {
		if strings.Count(out, name+"=") != 1 {
			t.Errorf("%s should appear exactly once in output, got:\n%s", name, out)
		}
		if strings.Contains(out, name+"=shouldnotappear") {
			t.Errorf("rule with reserved name %s leaked its From value into the output:\n%s", name, out)
		}
	}
	if !strings.Contains(out, "MY_VAR=shouldnotappear") {
		t.Errorf("non-reserved rule should still be emitted, got:\n%s", out)
	}
}

func TestBuildContent_simpleStringRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MY_VAR", From: "state"},
	}, map[string]any{"state": "staging"})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "MY_VAR=staging") {
		t.Errorf("expected MY_VAR=staging, got:\n%s", out)
	}
}

func TestBuildContent_boolFormatTrue(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "USE_HTTPS", From: "runtime.use_https", Format: "bool"},
	}, map[string]any{
		"runtime": map[string]any{"use_https": true},
	})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "USE_HTTPS=true") {
		t.Errorf("expected USE_HTTPS=true, got:\n%s", out)
	}
}

func TestBuildContent_boolFormatFalse(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "USE_HTTPS", From: "runtime.use_https", Format: "bool"},
	}, map[string]any{
		"runtime": map[string]any{"use_https": false},
	})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "USE_HTTPS=false") {
		t.Errorf("expected USE_HTTPS=false, got:\n%s", out)
	}
}

func TestBuildContent_intFormat(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "APP_PORT", From: "services.app.ports.http", Format: "int"},
	}, map[string]any{
		"services": map[string]any{
			"app": map[string]any{
				"ports": map[string]any{"http": 8080},
			},
		},
	})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "APP_PORT=8080") {
		t.Errorf("expected APP_PORT=8080, got:\n%s", out)
	}
}

func TestBuildContent_defaultFallback(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MISSING_VAR", From: "no.such.path", Default: "fallback"},
	}, map[string]any{})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "MISSING_VAR=fallback") {
		t.Errorf("expected MISSING_VAR=fallback, got:\n%s", out)
	}
}

func TestBuildContent_requiredMissingReturnsError(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "REQUIRED_VAR", From: "no.such.path", Required: true},
	}, map[string]any{})

	_, err := BuildContent(cfg)
	if err == nil {
		t.Error("expected error for required missing path, got nil")
	}
	if err != nil && !strings.Contains(err.Error(), "required") {
		t.Errorf("expected 'required' in error, got: %v", err)
	}
}

func TestBuildContent_whenFalsySkipsRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "TOOL_ADMINER", From: "tools.adminer.enabled", When: "tools.adminer.enabled", Format: "bool"},
	}, map[string]any{
		"tools": map[string]any{
			"adminer": map[string]any{"enabled": false},
		},
	})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(out, "TOOL_ADMINER") {
		t.Errorf("expected TOOL_ADMINER to be skipped when when-condition is falsy, got:\n%s", out)
	}
}

func TestBuildContent_whenTruthyIncludesRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "TOOL_ADMINER", From: "tools.adminer.enabled", When: "tools.adminer.enabled", Format: "bool"},
	}, map[string]any{
		"tools": map[string]any{
			"adminer": map[string]any{"enabled": true},
		},
	})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "TOOL_ADMINER=true") {
		t.Errorf("expected TOOL_ADMINER=true when when-condition is truthy, got:\n%s", out)
	}
}

func TestBuildContent_commentEmitted(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MY_VAR", From: "state", Comment: "Active state"},
	}, map[string]any{"state": "staging"})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "# Active state") {
		t.Errorf("expected comment in output, got:\n%s", out)
	}
}

// --- IsTruthy tests ---

func TestIsTruthy(t *testing.T) {
	cases := []struct {
		v    any
		want bool
	}{
		{nil, false},
		{false, false},
		{true, true},
		{0, false},
		{1, true},
		{"", false},
		{"false", false},
		{"0", false},
		{"true", true},
		{"staging", true},
		{map[string]any{}, true}, // unknown type → truthy
	}
	for _, tc := range cases {
		got := IsTruthy(tc.v)
		if got != tc.want {
			t.Errorf("IsTruthy(%#v) = %v, want %v", tc.v, got, tc.want)
		}
	}
}

// --- FormatValue tests ---

func TestFormatValue_boolTrue(t *testing.T) {
	if got := FormatValue(true, "bool"); got != "true" {
		t.Errorf("FormatValue(true, bool) = %q, want true", got)
	}
}

func TestFormatValue_boolFalse(t *testing.T) {
	if got := FormatValue(false, "bool"); got != "false" {
		t.Errorf("FormatValue(false, bool) = %q, want false", got)
	}
}

func TestFormatValue_intFormat(t *testing.T) {
	if got := FormatValue(8080, "int"); got != "8080" {
		t.Errorf("FormatValue(8080, int) = %q, want 8080", got)
	}
}

func TestFormatValue_stringPassthrough(t *testing.T) {
	if got := FormatValue("hello", ""); got != "hello" {
		t.Errorf("FormatValue(hello, ) = %q, want hello", got)
	}
}

func TestFormatValue_boolFormatNonBoolValue(t *testing.T) {
	// When format is bool but value is not a bool, falls through to Sprintf.
	if got := FormatValue("yes", "bool"); got != "yes" {
		t.Errorf("FormatValue(yes, bool) = %q, want yes", got)
	}
}

// --- Regression tests for data-driven tools (raw dot-path resolution) ---

func TestBuildContent_toolPortResolution(t *testing.T) {
	// Tool ports live under services.<name>.ports.<port-name> in the unified schema.
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "ADMINER_PORT", From: "services.adminer.ports.web", Format: "int"},
	}, map[string]any{
		"services": map[string]any{
			"adminer": map[string]any{
				"ports": map[string]any{"web": 8080},
			},
		},
	})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "ADMINER_PORT=8080") {
		t.Errorf("expected ADMINER_PORT=8080, got:\n%s", out)
	}
}

func TestBuildContent_toolHostResolution(t *testing.T) {
	// Tool hosts live under services.<name>.hosts.<host-name>.
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "ADMINER_HOST", From: "services.adminer.hosts.web"},
	}, map[string]any{
		"services": map[string]any{
			"adminer": map[string]any{
				"hosts": map[string]any{"web": "adminer.localhost"},
			},
		},
	})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "ADMINER_HOST=adminer.localhost") {
		t.Errorf("expected ADMINER_HOST=adminer.localhost, got:\n%s", out)
	}
}

// TestBuildContent_multiPortService exercises a service that declares two
// named ports — proves the loader/raw-injection roundtrip and the export
// rule resolution both handle multi-port maps.
func TestBuildContent_multiPortService(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "APP_HTTP_PORT", From: "services.app.ports.http", Format: "int"},
		{Name: "APP_GRPC_PORT", From: "services.app.ports.grpc", Format: "int"},
	}, map[string]any{
		"services": map[string]any{
			"app": map[string]any{
				"ports": map[string]any{"http": 8080, "grpc": 9090},
			},
		},
	})

	out, err := BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	for _, want := range []string{"APP_HTTP_PORT=8080", "APP_GRPC_PORT=9090"} {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q, got:\n%s", want, out)
		}
	}
}
