package envfile

import (
	"fmt"
	"strings"

	"github.com/semsemyonoff/dwe/internal/core/project/config"
	"github.com/semsemyonoff/dwe/internal/shared/hostid"
	"github.com/semsemyonoff/dwe/internal/shared/secrets"
)

// HostUID returns the UID to use for container builds.
// On macOS, Docker Desktop runs containers in a Linux VM where host UIDs don't
// map directly, so 1000 is the conventional user UID inside the image.
// On Linux, the actual host UID is used so file permissions match.
func HostUID() string { return hostid.UID() }

// HostGID returns the GID to use for container builds (same platform logic as HostUID).
func HostGID() string { return hostid.GID() }

// BuildContent renders the .env content from the export spec.
//
// System variables (emitted ahead of the export spec, not part of it):
//   - PROJECT              — project.name, verbatim
//   - UID                  — host UID for container builds (1000 on macOS, actual on Linux)
//   - GID                  — host GID for container builds (1000 on macOS, actual on Linux)
//   - COMPOSE_PROJECT_NAME — the compose project name dwe passes as -p:
//     workspace/docker.yml (or docker.local.yml) project_name, else
//     <prefix>-<name>, always lowercased. Omitted when the name resolves
//     empty (dwe then omits -p as well); resolution errors fail the render.
//
// baseDir is the project root (the directory holding workspace.yml); it is what
// the compose project name is resolved against.
//
// The names of these variables are reserved (see config.ReservedExportNames):
// LoadConfig rejects any export rule that tries to redeclare them, and this
// function defensively skips such rules in case it is called with a config
// that bypassed validation.
func BuildContent(cfg *config.DweConfig, baseDir string) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by dwe — do not edit manually\n\n")

	// A wrong compose project name in .env is exactly the split-brain this
	// export exists to remove, so a resolution failure stops the render rather
	// than falling back to a guessed name.
	composeName, err := config.ResolveComposeProjectName(baseDir, cfg)
	if err != nil {
		return "", fmt.Errorf("compose project name: %w", err)
	}

	// System variables: emitted regardless of export spec.
	systemValues := map[string]string{
		"PROJECT":              cfg.Project.Name,
		"UID":                  HostUID(),
		"GID":                  HostGID(),
		"COMPOSE_PROJECT_NAME": composeName,
	}
	// System-value sources, for the undecrypted-secret guard below.
	systemSources := map[string]string{
		"PROJECT":              "project.name",
		"COMPOSE_PROJECT_NAME": "the compose project name (docker.yml project_name or project.prefix/name)",
	}
	for _, name := range config.ReservedExportNames {
		value := systemValues[name]
		if name == "COMPOSE_PROJECT_NAME" && value == "" {
			// Mirrors the compose wrapper omitting -p: an empty assignment
			// would override compose's own default with nothing.
			continue
		}
		if err := checkValue(name, systemSources[name], value); err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "%s=%s\n", name, value)
	}

	for _, rule := range cfg.Exports.Env {
		// Defense-in-depth: if a caller built a config without LoadConfig,
		// silently drop reserved-name rules rather than producing duplicates.
		if config.IsReservedExportName(rule.Name) {
			continue
		}
		// Evaluate when condition: skip rule if the path resolves to a falsy value.
		if rule.When != "" {
			v, _ := config.ResolvePath(cfg.Raw, rule.When)
			if !IsTruthy(v) {
				continue
			}
		}

		// Resolve value from the effective config.
		// For typed formats (bool, int), always use the resolved value even when
		// falsy (false, 0) so that TOOL_FOO=false and PORT=0 are emitted correctly.
		// For string format, an empty resolved value falls back to default.
		value := rule.Default
		source := "the rule default"
		if v, ok := config.ResolvePath(cfg.Raw, rule.From); ok {
			if rule.Format == "bool" || rule.Format == "int" || IsTruthy(v) {
				value = FormatValue(v, rule.Format)
				source = rule.From
			}
		} else if rule.Required && value == "" {
			return "", fmt.Errorf("export %q: required path %q not found in config", rule.Name, rule.From)
		}

		if err := checkValue("exports.env["+rule.Name+"]", source, value); err != nil {
			return "", err
		}

		if rule.Comment != "" {
			fmt.Fprintf(&b, "# %s\n", rule.Comment)
		}
		fmt.Fprintf(&b, "%s=%s\n", rule.Name, value)
	}

	return b.String(), nil
}

// checkValue runs every guard a value must clear before it is written to the
// .env file as a bare `NAME=value` line.
func checkValue(label, source, value string) error {
	if err := checkNotMarker(label, source, value); err != nil {
		return err
	}
	return checkSingleLine(label, source, value)
}

// checkSingleLine refuses a value carrying a line break.
//
// Values are written unquoted and unescaped, so the second and later lines of a
// multi-line value are parsed by compose as further `.env` entries: the value
// is silently truncated to its first line, and a line that happens to look like
// `NAME=…` injects a variable nobody declared. Multi-line material is exactly
// what `dwe secrets set --stdin` accepts (a PEM key, a service-account blob),
// which makes the silent truncation likeliest on the values that can least
// afford it.
//
// Refuse rather than quote: the .env dialect compose accepts is narrower than
// the shell's, and a credential that half-survives an escaping scheme is worse
// than one that fails loudly at render time.
func checkSingleLine(label, source, value string) error {
	if !strings.ContainsAny(value, "\n\r") {
		return nil
	}
	if source == "" {
		source = "the config"
	}
	return fmt.Errorf("%s: value at %s spans multiple lines, which the .env format cannot represent — "+
		"deliver multi-line material through a config-pack file instead of exports.env", label, source)
}

// checkNotMarker refuses a value that is still an undecrypted secret marker.
//
// The .env file is the one plaintext sink the container reads, and neither
// `dwe render env` nor the auto-regeneration sites run preflight (dwe run even
// renders .env *before* its preflight), so the guard lives here: a missing
// identity must never silently publish ciphertext as if it were the
// credential.
//
// ContainsMarker, not IsMarker — matching the sibling guard in
// execution/templates/config. A rule whose from: resolves to a map or a
// sequence is formatted with %v, so an unresolved marker arrives embedded in
// `map[password:ENC[age:…]]` and an exact-match test would wave it through.
func checkNotMarker(label, source, value string) error {
	if !secrets.ContainsMarker(value) {
		return nil
	}
	if source == "" {
		source = "the config"
	}
	return fmt.Errorf("%s: value at %s is an undecrypted secret — see 'dwe secrets status'", label, source)
}

// IsTruthy returns whether v represents a truthy config value.
// nil, false, 0, "", "false", "0" are all falsy.
func IsTruthy(v any) bool {
	if v == nil {
		return false
	}
	switch val := v.(type) {
	case bool:
		return val
	case int:
		return val != 0
	case float64:
		return val != 0
	case string:
		return val != "" && val != "false" && val != "0"
	default:
		return true
	}
}

// FormatValue converts a raw config value to a string for .env output.
// The format hint influences how ambiguous types (e.g. bool) are rendered.
func FormatValue(v any, format string) string {
	if format == "bool" {
		if val, ok := v.(bool); ok {
			if val {
				return "true"
			}
			return "false"
		}
	}
	return fmt.Sprintf("%v", v)
}
