// Package spec defines the contract every builtin implementation satisfies and
// the helpers domain subpackages share. It is the leaf-most package in the
// builtin tree so that domain subpackages (containers, services, fs, env,
// interaction) can import it without introducing cycles with the root
// builtin/ package, which itself imports spec to expose type aliases.
package spec

import (
	"context"
	"io"

	"github.com/semsemyonoff/dwe/internal/core/project/config"
	"github.com/semsemyonoff/dwe/internal/shared/render"
)

// ExecContext holds the runtime context passed to every builtin execution.
type ExecContext struct {
	// Config is the merged dwe configuration.
	Config *config.DweConfig
	// DockerConfig is the resolved docker policy. Callers must pre-normalise
	// missing-file (os.ErrNotExist) to &config.DockerConfig{} so builtins can
	// pass it directly to docker.NewCompose without nil-checks.
	DockerConfig *config.DockerConfig
	// ProjectRoot is the absolute path to the project root (directory of workspace.yml).
	ProjectRoot string
	// Output is the render writer for styled terminal output. All builtin
	// output flows through this single channel — the executor wires it to
	// the per-step lineTee so frames reach Reporter.StepOutput like every
	// other child line.
	Output *render.Writer
	// Stdin is the reader used for interactive prompts. Defaults to os.Stdin when nil.
	Stdin io.Reader
	// SkipConfirm suppresses all confirm builtins (e.g. when --yes is passed).
	SkipConfirm bool
	// ConfirmFunc is an optional callback for interactive confirmation.
	// When non-nil, the confirm builtin uses it instead of reading from stdin.
	// Returns (true, nil) if confirmed, (false, nil) if denied.
	ConfirmFunc func(msg, okMsg, stopMsg string) (bool, error)
}

// Builtin is an engine-internal pipeline action.
type Builtin interface {
	// Validate checks that the with parameters are valid before the pipeline runs.
	Validate(with map[string]any) error
	// Describe returns a short human-readable description used in plan output.
	Describe(with map[string]any) string
	// Run executes the builtin action. ctx propagates cancellation; long-running
	// loops (e.g. health polling) should select on ctx.Done() to abort promptly.
	Run(ctx context.Context, with map[string]any, ectx ExecContext) error
}

// Kind classifies how a builtin may be invoked.
type Kind int

const (
	// KindAction builtins are user-callable step actions (confirm, message, service_configs_copy, etc.).
	// They run in the body of a deploy/lifecycle step authored in YAML.
	KindAction Kind = iota
	// KindPredicate builtins are read-only checks used in check: positions and validate.yml cmd: entries.
	// They MUST NOT have side effects (no volume removal, no container starts).
	KindPredicate
	// KindInternal builtins are engine-only; they cannot be invoked from user-authored YAML.
	// They are injected by the engine itself (e.g. daemons_reap in the synthetic _auto_reap_daemons phase,
	// or docker_daemon_start/stop/logs generated by daemon command expansion).
	KindInternal
)

// CallerContext identifies who is invoking a builtin, used for kind/context gating.
type CallerContext int

const (
	// CtxUserYAML is used when a builtin is invoked from user-authored YAML (deploy.yml step body,
	// commands.yml type: builtin). Only KindAction builtins are allowed here.
	CtxUserYAML CallerContext = iota
	// CtxPredicate is used when a builtin is invoked from a check: position in a pipeline step
	// or from a validate.yml cmd: entry. KindAction and KindPredicate builtins are both allowed here.
	CtxPredicate
	// CtxInternal is used when a builtin is invoked by the engine itself (engine-synthetic phases
	// or daemon-generated virtual commands). Only KindInternal builtins are allowed here.
	CtxInternal
)

// Entry pairs a Builtin implementation with its kind metadata. Domain
// subpackages construct Entry values in their Builtins() providers, and the
// root builtin/ registry assembles those into the global registry map.
type Entry struct {
	Impl Builtin
	Kind Kind
}
