package render

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/semsemyonoff/dwe/internal/cli/cmdctx"
	"github.com/semsemyonoff/dwe/internal/core/project/config"
	"github.com/semsemyonoff/dwe/internal/shared/envfile"
)

// makeEnvCfg builds a DweConfig with the given export rules and raw map.
func makeEnvCfg(rules []config.ExportRule, raw map[string]any) *config.DweConfig {
	return &config.DweConfig{
		Project: config.ProjectConfig{Name: "laravel", Prefix: "devbox"},
		Exports: config.ExportsConfig{Env: rules},
		Raw:     raw,
	}
}

func TestBuildEnvContent_alwaysEmitsProjectAndHeader(t *testing.T) {
	cfg := makeEnvCfg(nil, map[string]any{})
	out, err := envfile.BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "# Generated by devbox") {
		t.Error("missing header comment")
	}
	if !strings.Contains(out, "PROJECT=laravel") {
		t.Error("missing PROJECT system variable")
	}
}

func TestBuildEnvContent_simpleStringRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MY_VAR", From: "state"},
	}, map[string]any{"state": "staging"})

	out, err := envfile.BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "MY_VAR=staging") {
		t.Errorf("expected MY_VAR=staging, got:\n%s", out)
	}
}

func TestBuildEnvContent_boolFormatTrue(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "USE_HTTPS", From: "runtime.use_https", Format: "bool"},
	}, map[string]any{
		"runtime": map[string]any{"use_https": true},
	})

	out, err := envfile.BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "USE_HTTPS=true") {
		t.Errorf("expected USE_HTTPS=true, got:\n%s", out)
	}
}

func TestBuildEnvContent_boolFormatFalse(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "USE_HTTPS", From: "runtime.use_https", Format: "bool"},
	}, map[string]any{
		"runtime": map[string]any{"use_https": false},
	})

	out, err := envfile.BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "USE_HTTPS=false") {
		t.Errorf("expected USE_HTTPS=false, got:\n%s", out)
	}
}

func TestBuildEnvContent_intFormat(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "APP_PORT", From: "services.app.ports.http", Format: "int"},
	}, map[string]any{
		"services": map[string]any{
			"app": map[string]any{
				"ports": map[string]any{"http": 8080},
			},
		},
	})

	out, err := envfile.BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "APP_PORT=8080") {
		t.Errorf("expected APP_PORT=8080, got:\n%s", out)
	}
}

func TestBuildEnvContent_defaultFallback(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MISSING_VAR", From: "no.such.path", Default: "fallback"},
	}, map[string]any{})

	out, err := envfile.BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "MISSING_VAR=fallback") {
		t.Errorf("expected MISSING_VAR=fallback, got:\n%s", out)
	}
}

func TestBuildEnvContent_requiredMissingReturnsError(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "REQUIRED_VAR", From: "no.such.path", Required: true},
	}, map[string]any{})

	_, err := envfile.BuildContent(cfg)
	if err == nil {
		t.Error("expected error for required missing path, got nil")
	}
	if err != nil && !strings.Contains(err.Error(), "required") {
		t.Errorf("expected 'required' in error, got: %v", err)
	}
}

func TestBuildEnvContent_whenFalsySkipsRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "TOOL_ADMINER", From: "tools.adminer.enabled", When: "tools.adminer.enabled", Format: "bool"},
	}, map[string]any{
		"tools": map[string]any{
			"adminer": map[string]any{"enabled": false},
		},
	})

	out, err := envfile.BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(out, "TOOL_ADMINER") {
		t.Errorf("expected TOOL_ADMINER to be skipped when when-condition is falsy, got:\n%s", out)
	}
}

func TestBuildEnvContent_whenTruthyIncludesRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "TOOL_ADMINER", From: "tools.adminer.enabled", When: "tools.adminer.enabled", Format: "bool"},
	}, map[string]any{
		"tools": map[string]any{
			"adminer": map[string]any{"enabled": true},
		},
	})

	out, err := envfile.BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "TOOL_ADMINER=true") {
		t.Errorf("expected TOOL_ADMINER=true when when-condition is truthy, got:\n%s", out)
	}
}

func TestBuildEnvContent_commentEmitted(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MY_VAR", From: "state", Comment: "Active state"},
	}, map[string]any{"state": "staging"})

	out, err := envfile.BuildContent(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "# Active state") {
		t.Errorf("expected comment in output, got:\n%s", out)
	}
}

// --- IsTruthy tests ---

func TestIsTruthy(t *testing.T) {
	cases := []struct {
		v    any
		want bool
	}{
		{nil, false},
		{false, false},
		{true, true},
		{0, false},
		{1, true},
		{"", false},
		{"false", false},
		{"0", false},
		{"true", true},
		{"staging", true},
		{map[string]any{}, true}, // unknown type → truthy
	}
	for _, tc := range cases {
		got := envfile.IsTruthy(tc.v)
		if got != tc.want {
			t.Errorf("IsTruthy(%#v) = %v, want %v", tc.v, got, tc.want)
		}
	}
}

// --- FormatValue tests ---

func TestFormatValue_boolTrue(t *testing.T) {
	if got := envfile.FormatValue(true, "bool"); got != "true" {
		t.Errorf("FormatValue(true, bool) = %q, want true", got)
	}
}

func TestFormatValue_boolFalse(t *testing.T) {
	if got := envfile.FormatValue(false, "bool"); got != "false" {
		t.Errorf("FormatValue(false, bool) = %q, want false", got)
	}
}

func TestFormatValue_intFormat(t *testing.T) {
	if got := envfile.FormatValue(8080, "int"); got != "8080" {
		t.Errorf("FormatValue(8080, int) = %q, want 8080", got)
	}
}

func TestFormatValue_stringPassthrough(t *testing.T) {
	if got := envfile.FormatValue("hello", ""); got != "hello" {
		t.Errorf("FormatValue(hello, ) = %q, want hello", got)
	}
}

func TestFormatValue_boolFormatNonBoolValue(t *testing.T) {
	// When format is bool but value is not a bool, falls through to Sprintf.
	if got := envfile.FormatValue("yes", "bool"); got != "yes" {
		t.Errorf("FormatValue(yes, bool) = %q, want yes", got)
	}
}

// TestRunRenderEnv_ToFile verifies the file-writing path: a non-empty
// outputPath causes the rendered .env to land at that path on disk.
func TestRunRenderEnv_ToFile(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "workspace.yml")
	yml := "schema_version: \"2\"\nproject:\n  name: testproject\n  prefix: devbox\n"
	if err := os.WriteFile(cfgPath, []byte(yml), 0o644); err != nil {
		t.Fatal(err)
	}

	out := filepath.Join(dir, ".env")
	if err := runRenderEnv(&cmdctx.RootFlags{ConfigPath: cfgPath}, out); err != nil {
		t.Fatalf("runRenderEnv: %v", err)
	}

	body, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read .env: %v", err)
	}
	if !strings.Contains(string(body), "PROJECT=testproject") {
		t.Errorf("output missing PROJECT=testproject: %q", body)
	}
}

// TestRunRenderEnv_InvalidConfig verifies that a config-load failure is
// surfaced as an error (not silently dropped).
func TestRunRenderEnv_InvalidConfig(t *testing.T) {
	err := runRenderEnv(&cmdctx.RootFlags{ConfigPath: "/nonexistent/devbox.yml"}, "/tmp/whatever.env")
	if err == nil {
		t.Fatal("expected error for missing config, got nil")
	}
	if !strings.Contains(err.Error(), "loading config") {
		t.Errorf("err = %v, want one wrapping 'loading config'", err)
	}
}
