package render

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/semsemyonoff/dwe/internal/cli/cmdctx"
	"github.com/semsemyonoff/dwe/internal/core/project/config"
	"github.com/semsemyonoff/dwe/internal/shared/envfile"

	"github.com/spf13/cobra"
)

// makeEnvCfg builds a DweConfig with the given export rules and raw map.
//
// The BuildContent calls below pass an empty baseDir, which skips the
// docker.yml read: COMPOSE_PROJECT_NAME then falls back to the lowercased
// FullName(). The resolver's own precedence rules are covered in
// internal/shared/envfile.
func makeEnvCfg(rules []config.ExportRule, raw map[string]any) *config.DweConfig {
	return &config.DweConfig{
		Project: config.ProjectConfig{Name: "laravel", Prefix: "dwe"},
		Exports: config.ExportsConfig{Env: rules},
		Raw:     raw,
	}
}

func TestBuildEnvContent_alwaysEmitsProjectAndHeader(t *testing.T) {
	cfg := makeEnvCfg(nil, map[string]any{})
	out, err := envfile.BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "# Generated by dwe") {
		t.Error("missing header comment")
	}
	if !strings.Contains(out, "PROJECT=laravel") {
		t.Error("missing PROJECT system variable")
	}
}

func TestBuildEnvContent_simpleStringRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MY_VAR", From: "env"},
	}, map[string]any{"env": "staging"})

	out, err := envfile.BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "MY_VAR=staging") {
		t.Errorf("expected MY_VAR=staging, got:\n%s", out)
	}
}

func TestBuildEnvContent_boolFormatTrue(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "USE_HTTPS", From: "runtime.use_https", Format: "bool"},
	}, map[string]any{
		"runtime": map[string]any{"use_https": true},
	})

	out, err := envfile.BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "USE_HTTPS=true") {
		t.Errorf("expected USE_HTTPS=true, got:\n%s", out)
	}
}

func TestBuildEnvContent_boolFormatFalse(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "USE_HTTPS", From: "runtime.use_https", Format: "bool"},
	}, map[string]any{
		"runtime": map[string]any{"use_https": false},
	})

	out, err := envfile.BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "USE_HTTPS=false") {
		t.Errorf("expected USE_HTTPS=false, got:\n%s", out)
	}
}

func TestBuildEnvContent_intFormat(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "APP_PORT", From: "services.app.ports.http", Format: "int"},
	}, map[string]any{
		"services": map[string]any{
			"app": map[string]any{
				"ports": map[string]any{"http": 8080},
			},
		},
	})

	out, err := envfile.BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "APP_PORT=8080") {
		t.Errorf("expected APP_PORT=8080, got:\n%s", out)
	}
}

func TestBuildEnvContent_defaultFallback(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MISSING_VAR", From: "no.such.path", Default: "fallback"},
	}, map[string]any{})

	out, err := envfile.BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "MISSING_VAR=fallback") {
		t.Errorf("expected MISSING_VAR=fallback, got:\n%s", out)
	}
}

func TestBuildEnvContent_requiredMissingReturnsError(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "REQUIRED_VAR", From: "no.such.path", Required: true},
	}, map[string]any{})

	_, err := envfile.BuildContent(cfg, "")
	if err == nil {
		t.Error("expected error for required missing path, got nil")
	}
	if err != nil && !strings.Contains(err.Error(), "required") {
		t.Errorf("expected 'required' in error, got: %v", err)
	}
}

func TestBuildEnvContent_whenFalsySkipsRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "TOOL_ADMINER", From: "tools.adminer.enabled", When: "tools.adminer.enabled", Format: "bool"},
	}, map[string]any{
		"tools": map[string]any{
			"adminer": map[string]any{"enabled": false},
		},
	})

	out, err := envfile.BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(out, "TOOL_ADMINER") {
		t.Errorf("expected TOOL_ADMINER to be skipped when when-condition is falsy, got:\n%s", out)
	}
}

func TestBuildEnvContent_whenTruthyIncludesRule(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "TOOL_ADMINER", From: "tools.adminer.enabled", When: "tools.adminer.enabled", Format: "bool"},
	}, map[string]any{
		"tools": map[string]any{
			"adminer": map[string]any{"enabled": true},
		},
	})

	out, err := envfile.BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "TOOL_ADMINER=true") {
		t.Errorf("expected TOOL_ADMINER=true when when-condition is truthy, got:\n%s", out)
	}
}

func TestBuildEnvContent_commentEmitted(t *testing.T) {
	cfg := makeEnvCfg([]config.ExportRule{
		{Name: "MY_VAR", From: "env", Comment: "Active env"},
	}, map[string]any{"env": "staging"})

	out, err := envfile.BuildContent(cfg, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "# Active env") {
		t.Errorf("expected comment in output, got:\n%s", out)
	}
}

// --- IsTruthy tests ---

func TestIsTruthy(t *testing.T) {
	cases := []struct {
		v    any
		want bool
	}{
		{nil, false},
		{false, false},
		{true, true},
		{0, false},
		{1, true},
		{"", false},
		{"false", false},
		{"0", false},
		{"true", true},
		{"staging", true},
		{map[string]any{}, true}, // unknown type → truthy
	}
	for _, tc := range cases {
		got := envfile.IsTruthy(tc.v)
		if got != tc.want {
			t.Errorf("IsTruthy(%#v) = %v, want %v", tc.v, got, tc.want)
		}
	}
}

// --- FormatValue tests ---

func TestFormatValue_boolTrue(t *testing.T) {
	if got := envfile.FormatValue(true, "bool"); got != "true" {
		t.Errorf("FormatValue(true, bool) = %q, want true", got)
	}
}

func TestFormatValue_boolFalse(t *testing.T) {
	if got := envfile.FormatValue(false, "bool"); got != "false" {
		t.Errorf("FormatValue(false, bool) = %q, want false", got)
	}
}

func TestFormatValue_intFormat(t *testing.T) {
	if got := envfile.FormatValue(8080, "int"); got != "8080" {
		t.Errorf("FormatValue(8080, int) = %q, want 8080", got)
	}
}

func TestFormatValue_stringPassthrough(t *testing.T) {
	if got := envfile.FormatValue("hello", ""); got != "hello" {
		t.Errorf("FormatValue(hello, ) = %q, want hello", got)
	}
}

func TestFormatValue_boolFormatNonBoolValue(t *testing.T) {
	// When format is bool but value is not a bool, falls through to Sprintf.
	if got := envfile.FormatValue("yes", "bool"); got != "yes" {
		t.Errorf("FormatValue(yes, bool) = %q, want yes", got)
	}
}

// TestRunRenderEnv_ToFile verifies the file-writing path: a non-empty
// outputPath causes the rendered .env to land at that path on disk.
func TestRunRenderEnv_ToFile(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "workspace.yml")
	yml := "schema_version: \"2\"\nproject:\n  name: testproject\n  prefix: dwe\n"
	if err := os.WriteFile(cfgPath, []byte(yml), 0o644); err != nil {
		t.Fatal(err)
	}

	out := filepath.Join(dir, ".env")
	if err := runRenderEnv(newTestEnvCmd(), &cmdctx.RootFlags{ConfigPath: cfgPath}, out); err != nil {
		t.Fatalf("runRenderEnv: %v", err)
	}

	body, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read .env: %v", err)
	}
	if !strings.Contains(string(body), "PROJECT=testproject") {
		t.Errorf("output missing PROJECT=testproject: %q", body)
	}
}

// TestRunRenderEnv_ComposeProjectNameFromDockerYML pins the baseDir this
// command threads into envfile. The parameter is the only thing that makes
// COMPOSE_PROJECT_NAME follow workspace/docker.yml, and a wrong value fails
// silently: envfile.BuildContent(cfg, "") returns <prefix>-<name> with no
// error, so .env would carry a different project than the -p dwe passes —
// exactly the split-brain the export exists to remove. Asserting only
// PROJECT= (as the sibling test does) cannot see that.
func TestRunRenderEnv_ComposeProjectNameFromDockerYML(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "workspace.yml")
	yml := "schema_version: \"2\"\nproject:\n  name: testproject\n  prefix: dwe\n"
	if err := os.WriteFile(cfgPath, []byte(yml), 0o644); err != nil {
		t.Fatal(err)
	}
	wsDir := filepath.Join(dir, "workspace")
	if err := os.MkdirAll(wsDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(wsDir, "docker.yml"), []byte("project_name: Custom_Scope\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	out := filepath.Join(dir, ".env")
	if err := runRenderEnv(newTestEnvCmd(), &cmdctx.RootFlags{ConfigPath: cfgPath}, out); err != nil {
		t.Fatalf("runRenderEnv: %v", err)
	}

	body, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read .env: %v", err)
	}
	if !strings.Contains(string(body), "COMPOSE_PROJECT_NAME=custom_scope\n") {
		t.Errorf("expected COMPOSE_PROJECT_NAME=custom_scope (lowercased docker.yml project_name), got:\n%s", body)
	}
}

// TestRunRenderEnv_InvalidConfig verifies that a config-load failure is
// surfaced as an error (not silently dropped).
func TestRunRenderEnv_InvalidConfig(t *testing.T) {
	err := runRenderEnv(newTestEnvCmd(), &cmdctx.RootFlags{ConfigPath: "/nonexistent/workspace.yml"}, "/tmp/whatever.env")
	if err == nil {
		t.Fatal("expected error for missing config, got nil")
	}
	if !strings.Contains(err.Error(), "loading config") {
		t.Errorf("err = %v, want one wrapping 'loading config'", err)
	}
}

// newTestEnvCmd returns a cobra command whose streams are captured, so a test
// can assert on what `dwe render env` writes where. The warning path exists
// only because the command threads its own streams — a bare fmt.Print would be
// invisible here.
func newTestEnvCmd() *cobra.Command { cmd, _, _ := newCapturingEnvCmd(); return cmd }

func newCapturingEnvCmd() (*cobra.Command, *bytes.Buffer, *bytes.Buffer) {
	var out, errBuf bytes.Buffer
	cmd := &cobra.Command{}
	cmd.SetOut(&out)
	cmd.SetErr(&errBuf)
	return cmd, &out, &errBuf
}

// writeUnresolvedExportProject lays down a project whose exports.env has one
// resolving rule and one whose from: is a typo.
func writeUnresolvedExportProject(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	yml := `schema_version: "2"
project:
  name: testproject
  prefix: dwe
vars:
  here: yes
exports:
  env:
    - name: OK_VAR
      from: vars.here
    - name: MISSING_VAR
      from: vars.typo
`
	if err := os.WriteFile(filepath.Join(dir, "workspace.yml"), []byte(yml), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// TestRunRenderEnv_WarnsOnUnresolvedRule pins the split: the warning goes to
// stderr and the content to stdout, so `dwe render env > .env` stays byte-
// identical to BuildContent while the user still sees why MISSING_VAR is empty.
func TestRunRenderEnv_WarnsOnUnresolvedRule(t *testing.T) {
	dir := writeUnresolvedExportProject(t)
	cfgPath := filepath.Join(dir, "workspace.yml")

	cmd, out, errBuf := newCapturingEnvCmd()
	if err := runRenderEnv(cmd, &cmdctx.RootFlags{ConfigPath: cfgPath}, ""); err != nil {
		t.Fatalf("runRenderEnv: %v", err)
	}

	wantWarn := `warning: exports.env[MISSING_VAR]: from "vars.typo" does not resolve — rendered empty` + "\n"
	if errBuf.String() != wantWarn {
		t.Errorf("stderr = %q, want %q", errBuf.String(), wantWarn)
	}

	cfg, err := config.LoadConfig(cfgPath)
	if err != nil {
		t.Fatalf("LoadConfig: %v", err)
	}
	want, err := envfile.BuildContent(cfg, dir)
	if err != nil {
		t.Fatalf("BuildContent: %v", err)
	}
	if out.String() != want {
		t.Errorf("stdout = %q, want it byte-identical to BuildContent %q", out.String(), want)
	}
	if !strings.Contains(out.String(), "MISSING_VAR=\n") {
		t.Errorf("expected a bare MISSING_VAR= line, got:\n%s", out.String())
	}
}

// TestRunRenderEnv_WarnsOnUnresolvedRuleToFile: the warning is about the
// content, not the sink, so --out gets it too.
func TestRunRenderEnv_WarnsOnUnresolvedRuleToFile(t *testing.T) {
	dir := writeUnresolvedExportProject(t)
	cmd, out, errBuf := newCapturingEnvCmd()

	target := filepath.Join(dir, ".env")
	if err := runRenderEnv(cmd, &cmdctx.RootFlags{ConfigPath: filepath.Join(dir, "workspace.yml")}, target); err != nil {
		t.Fatalf("runRenderEnv: %v", err)
	}
	if !strings.Contains(errBuf.String(), "exports.env[MISSING_VAR]") {
		t.Errorf("stderr = %q, want the MISSING_VAR warning", errBuf.String())
	}
	if out.Len() != 0 {
		t.Errorf("stdout = %q, want empty on the --out path", out.String())
	}
	body, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read .env: %v", err)
	}
	if !strings.Contains(string(body), "MISSING_VAR=\n") {
		t.Errorf("expected MISSING_VAR= in the written file, got:\n%s", body)
	}
}

// TestRunRenderEnv_NoWarningInJSONMode holds the output-mode contract: JSON
// consumers get no stray text on either stream.
func TestRunRenderEnv_NoWarningInJSONMode(t *testing.T) {
	dir := writeUnresolvedExportProject(t)
	cmd, _, errBuf := newCapturingEnvCmd()

	flags := &cmdctx.RootFlags{ConfigPath: filepath.Join(dir, "workspace.yml"), Output: "json"}
	if err := runRenderEnv(cmd, flags, ""); err != nil {
		t.Fatalf("runRenderEnv: %v", err)
	}
	if errBuf.Len() != 0 {
		t.Errorf("stderr = %q, want empty under --output json", errBuf.String())
	}
}

// TestRunRenderEnv_SilentWhenEverythingResolves guards against a warning that
// fires on a healthy project.
func TestRunRenderEnv_SilentWhenEverythingResolves(t *testing.T) {
	dir := t.TempDir()
	yml := `schema_version: "2"
project:
  name: testproject
  prefix: dwe
vars:
  here: yes
exports:
  env:
    - name: OK_VAR
      from: vars.here
    - name: WITH_DEFAULT
      from: vars.typo
      default: fallback
`
	cfgPath := filepath.Join(dir, "workspace.yml")
	if err := os.WriteFile(cfgPath, []byte(yml), 0o644); err != nil {
		t.Fatal(err)
	}

	cmd, _, errBuf := newCapturingEnvCmd()
	if err := runRenderEnv(cmd, &cmdctx.RootFlags{ConfigPath: cfgPath}, ""); err != nil {
		t.Fatalf("runRenderEnv: %v", err)
	}
	if errBuf.Len() != 0 {
		t.Errorf("stderr = %q, want empty", errBuf.String())
	}
}
