#!/bin/bash
# Generate content-hash manifest for embedded documentation.
# Usage: gen-docs-content-hashes.sh <output-file>
# Generates a Go source file with SHA256 hashes of all markdown files
# in docs/reference and docs/internals.

set -e

OUTPUT_FILE="${1:-internal/core/docs/content_hashes_gen.go}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Collect all .md files from the source directories and compute hashes
# Use awk to build the map entries sorted by key
{
    echo "// Code generated by scripts/gen-docs-content-hashes.sh; DO NOT EDIT."
    echo ""
    echo "package docs"
    echo ""
    echo "// ContentHashes maps relative file paths to their content SHA256 hashes (first 12 hex chars)."
    echo "// Generated from docs/reference and docs/internals at build time."
    echo "// See docs/reference/docs/index.md for details on the hash-based staleness check."
    echo "var ContentHashes = map[string]string{"

    # Find all markdown files in docs/reference and docs/internals
    # For each file, compute sha256 and take first 12 hex chars
    # Build map entries as "path": "hash"
    find docs/reference docs/internals -name "*.md" -type f 2>/dev/null | while read -r file; do
        # Get the relative path (e.g., "reference/config/devbox.md")
        relpath="${file#docs/}"

        # Compute sha256 hash and take first 12 chars
        # Handle both sha256sum (Linux) and shasum -a 256 (macOS)
        if command -v sha256sum &> /dev/null; then
            hash=$(sha256sum "$file" | cut -c1-12)
        elif command -v shasum &> /dev/null; then
            hash=$(shasum -a 256 "$file" | cut -c1-12)
        else
            echo "Warning: Neither sha256sum nor shasum found, skipping hash computation" >&2
            continue
        fi

        # Escape any double quotes in the path (unlikely but safe)
        escaped_relpath="${relpath//\"/\\\"}"

        # Output map entry: "path": "hash",
        echo "    \"$escaped_relpath\": \"$hash\","
    done | sort -k1

    echo "}"
} > "$OUTPUT_FILE.tmp"

# Format with gofmt for stable whitespace
gofmt -s -w "$OUTPUT_FILE.tmp" 2>/dev/null || true

# Atomically move the temp file to the target
mv "$OUTPUT_FILE.tmp" "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
