#!/bin/bash
# Generate content-hash manifest for embedded documentation.
# Usage: gen-docs-content-hashes.sh <output-file>
# Generates a Go source file with SHA256 hashes of all markdown files
# in docs/reference, docs/guides, and docs/internals.

set -e

OUTPUT_FILE="${1:-internal/core/docs/content_hashes_gen.go}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Collect all .md files from the source directories and compute hashes
# Use awk to build the map entries sorted by key
{
    echo "// Code generated by scripts/gen-docs-content-hashes.sh; DO NOT EDIT."
    echo ""
    echo "package docs"
    echo ""
    echo "// ContentHashes maps relative file paths to their content SHA256 hashes (first 12 hex chars)."
    echo "// Generated from docs/reference, docs/guides, and docs/internals at build time."
    echo "// See docs/reference/docs/index.md for details on the hash-based staleness check."
    echo "var ContentHashes = map[string]string{"

    # Build map entries from all markdown files. We feed two inputs into the
    # same pipeline so the output stays sorted and there is one hash branch:
    #   - markdown files under docs/reference, docs/guides, and docs/internals
    #     (relpath = "${file#docs/}", e.g. "reference/config/workspace.md")
    #   - the repo-root README.md as a flat top-level topic
    #     (relpath = "README.md")
    {
        find docs/reference docs/guides docs/internals -name "*.md" -type f 2>/dev/null
        if [ -f "README.md" ]; then
            echo "README.md"
        fi
    } | while read -r file; do
        relpath="${file#docs/}"

        if command -v sha256sum &> /dev/null; then
            hash=$(sha256sum "$file" | cut -c1-12)
        elif command -v shasum &> /dev/null; then
            hash=$(shasum -a 256 "$file" | cut -c1-12)
        else
            echo "Warning: Neither sha256sum nor shasum found, skipping hash computation" >&2
            continue
        fi

        escaped_relpath="${relpath//\"/\\\"}"

        echo "    \"$escaped_relpath\": \"$hash\","
    done | LC_ALL=C sort -k1

    echo "}"
} > "$OUTPUT_FILE.tmp"

# Format with gofmt for stable whitespace
gofmt -s -w "$OUTPUT_FILE.tmp" 2>/dev/null || true

# Atomically move the temp file to the target
mv "$OUTPUT_FILE.tmp" "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
