package command

import (
	"fmt"
	"os"
	"strings"

	"devbox-cli/internal/config"

	"github.com/spf13/cobra"
)

func newRenderCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:          "render",
		Short:        "Render derived artifacts from the merged devbox config",
		SilenceUsage: true,
	}
	cmd.AddCommand(newRenderEnvCmd(flags))
	return cmd
}

func newRenderEnvCmd(flags *rootFlags) *cobra.Command {
	var outputPath string

	cmd := &cobra.Command{
		Use:   "env",
		Short: "Generate .env from exports.env spec (stdout or --output <file>)",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runRenderEnv(flags, outputPath)
		},
		SilenceUsage: true,
	}
	cmd.Flags().StringVarP(&outputPath, "output", "o", "", "write to file instead of stdout")
	return cmd
}

func runRenderEnv(flags *rootFlags, outputPath string) error {
	cfg, err := config.LoadConfig(flags.configPath)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	content, err := buildEnvContent(cfg)
	if err != nil {
		return err
	}

	if outputPath == "" {
		fmt.Print(content)
		return nil
	}
	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}
	return nil
}

// buildEnvContent renders the .env content from the export spec.
//
// System variables (always emitted, not part of the export spec):
//   - PROJECT — project.name
func buildEnvContent(cfg *config.DevboxConfig) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by devbox-cli — do not edit manually\n\n")

	// System variable: always emitted regardless of export spec.
	fmt.Fprintf(&b, "PROJECT=%s\n", cfg.Project.Name)

	for _, rule := range cfg.Exports.Env {
		// Evaluate when condition: skip rule if the path resolves to a falsy value.
		if rule.When != "" {
			v, _ := config.ResolvePath(cfg.Raw, rule.When)
			if !isTruthy(v) {
				continue
			}
		}

		// Resolve value from the effective config.
		// A zero-valued source (empty string, 0, false) falls back to default,
		// matching the documented ExportRule behaviour.
		value := rule.Default
		if v, ok := config.ResolvePath(cfg.Raw, rule.From); ok && isTruthy(v) {
			value = formatValue(v, rule.Format)
		} else if rule.Required && value == "" {
			return "", fmt.Errorf("export %q: required path %q not found in config", rule.Name, rule.From)
		}

		if rule.Comment != "" {
			fmt.Fprintf(&b, "# %s\n", rule.Comment)
		}
		fmt.Fprintf(&b, "%s=%s\n", rule.Name, value)
	}

	return b.String(), nil
}

// isTruthy returns whether v represents a truthy config value.
// nil, false, 0, "", "false", "0" are all falsy.
func isTruthy(v any) bool {
	if v == nil {
		return false
	}
	switch val := v.(type) {
	case bool:
		return val
	case int:
		return val != 0
	case string:
		return val != "" && val != "false" && val != "0"
	default:
		return true
	}
}

// formatValue converts a raw config value to a string for .env output.
// The format hint influences how ambiguous types (e.g. bool) are rendered.
func formatValue(v any, format string) string {
	if format == "bool" {
		if val, ok := v.(bool); ok {
			if val {
				return "true"
			}
			return "false"
		}
	}
	return fmt.Sprintf("%v", v)
}
