package command

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"

	"devbox-cli/internal/config"
	"devbox-cli/internal/render"

	"github.com/spf13/cobra"
)

func newRenderCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:          "render",
		Short:        "Render derived artifacts from the merged devbox config",
		SilenceUsage: true,
	}
	cmd.AddCommand(newRenderEnvCmd(flags))
	cmd.AddCommand(newRenderIDECmd(flags))
	return cmd
}

func newRenderEnvCmd(flags *rootFlags) *cobra.Command {
	var outputPath string

	cmd := &cobra.Command{
		Use:   "env",
		Short: "Generate .env from exports.env spec (stdout or --output <file>)",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runRenderEnv(flags, outputPath)
		},
		SilenceUsage: true,
	}
	cmd.Flags().StringVarP(&outputPath, "output", "o", "", "write to file instead of stdout")
	return cmd
}

func runRenderEnv(flags *rootFlags, outputPath string) error {
	cfg, err := config.LoadConfig(flags.configPath)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	content, err := buildEnvContent(cfg)
	if err != nil {
		return err
	}

	if outputPath == "" {
		fmt.Print(content)
		return nil
	}
	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}
	return nil
}

// hostUID returns the UID to use for container builds.
// On macOS, Docker Desktop runs containers in a Linux VM where host UIDs don't
// map directly, so 1000 is the conventional user UID inside the image.
// On Linux, the actual host UID is used so file permissions match.
func hostUID() string {
	if runtime.GOOS == "darwin" {
		return "1000"
	}
	u, err := user.Current()
	if err != nil {
		return "1000"
	}
	return u.Uid
}

// hostGID returns the GID to use for container builds (same platform logic as hostUID).
func hostGID() string {
	if runtime.GOOS == "darwin" {
		return "1000"
	}
	u, err := user.Current()
	if err != nil {
		return "1000"
	}
	return u.Gid
}

// buildEnvContent renders the .env content from the export spec.
//
// System variables (always emitted, not part of the export spec):
//   - PROJECT — project.name
//   - UID     — host UID for container builds (1000 on macOS, actual on Linux)
//   - GID     — host GID for container builds (1000 on macOS, actual on Linux)
func buildEnvContent(cfg *config.DevboxConfig) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by devbox-cli — do not edit manually\n\n")

	// System variables: always emitted regardless of export spec.
	fmt.Fprintf(&b, "PROJECT=%s\n", cfg.Project.Name)
	fmt.Fprintf(&b, "UID=%s\n", hostUID())
	fmt.Fprintf(&b, "GID=%s\n", hostGID())

	for _, rule := range cfg.Exports.Env {
		// Evaluate when condition: skip rule if the path resolves to a falsy value.
		if rule.When != "" {
			v, _ := config.ResolvePath(cfg.Raw, rule.When)
			if !isTruthy(v) {
				continue
			}
		}

		// Resolve value from the effective config.
		// For typed formats (bool, int), always use the resolved value even when
		// falsy (false, 0) so that TOOL_FOO=false and PORT=0 are emitted correctly.
		// For string format, an empty resolved value falls back to default.
		value := rule.Default
		if v, ok := config.ResolvePath(cfg.Raw, rule.From); ok {
			if rule.Format == "bool" || rule.Format == "int" || isTruthy(v) {
				value = formatValue(v, rule.Format)
			}
		} else if rule.Required && value == "" {
			return "", fmt.Errorf("export %q: required path %q not found in config", rule.Name, rule.From)
		}

		if rule.Comment != "" {
			fmt.Fprintf(&b, "# %s\n", rule.Comment)
		}
		fmt.Fprintf(&b, "%s=%s\n", rule.Name, value)
	}

	return b.String(), nil
}

// regenEnv reloads config from configPath, regenerates .env in baseDir,
// and prints a confirmation. Called after any enable/disable mutation.
func regenEnv(configPath, baseDir string) error {
	cfg, err := config.LoadConfig(configPath)
	if err != nil {
		return fmt.Errorf("reload config: %w", err)
	}
	content, err := buildEnvContent(cfg)
	if err != nil {
		return err
	}
	envPath := filepath.Join(baseDir, ".env")
	if err := os.WriteFile(envPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", envPath, err)
	}
	render.Stdout().Info(fmt.Sprintf(".env regenerated → %s", envPath))
	return nil
}

// isTruthy returns whether v represents a truthy config value.
// nil, false, 0, "", "false", "0" are all falsy.
func isTruthy(v any) bool {
	if v == nil {
		return false
	}
	switch val := v.(type) {
	case bool:
		return val
	case int:
		return val != 0
	case string:
		return val != "" && val != "false" && val != "0"
	default:
		return true
	}
}

// formatValue converts a raw config value to a string for .env output.
// The format hint influences how ambiguous types (e.g. bool) are rendered.
func formatValue(v any, format string) string {
	if format == "bool" {
		if val, ok := v.(bool); ok {
			if val {
				return "true"
			}
			return "false"
		}
	}
	return fmt.Sprintf("%v", v)
}
