import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// Standard Starlight docs collection. Content under src/content/docs/ is
// GENERATED by scripts/sync-docs.mjs from the repo's docs/ tree (gitignored) —
// never edit it by hand; edit docs/reference or docs/guides and re-run the sync.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
