package bridge

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/semsemyonoff/dwe/internal/core/bridge/shimassets"
	"github.com/semsemyonoff/dwe/internal/core/project/config"
	shareddaemon "github.com/semsemyonoff/dwe/internal/shared/daemon"
	"github.com/semsemyonoff/dwe/internal/shared/trace"

	"gopkg.in/yaml.v3"
)

// Compose overlay generation (design D8). `.dwe/compose.bridge.yml` is
// dwe-owned machine state — regenerated (atomic, write-if-changed) by every
// command that performs `compose up`, the same ownership model as `.env`
// rendering and rendered service configs. It always contains exactly the
// currently enabled AND bridge-enabled services, so service toggles can
// never desync it; when nothing is bridged the file is DELETED (a stale
// leftover would otherwise re-enter the -f chain). User customization goes
// through workspace/local.yml, which sits after this overlay in the chain.

// BridgeMountTarget is the in-container mount point of the host's
// .dwe/bridge directory. The mount is read-only — connect() to a unix
// socket works on RO bind mounts (design D1.4).
const BridgeMountTarget = "/dwe-bridge"

// overlayHeader marks the file as generated; manual edits are unsupported
// and overwritten by the next compose-up command (design D8).
const overlayHeader = "# GENERATED by dwe — do not edit; customize via workspace/local.yml\n"

// overlayFilePerm is the generated overlay's file mode — plain config file,
// nothing secret in it (port/token deliberately live outside the overlay).
const overlayFilePerm = 0o644

// extraHostGateway makes host.docker.internal resolvable from containers on
// native Linux (Engine 20.10+); harmless on Docker Desktop (design D3).
const extraHostGateway = "host.docker.internal:host-gateway"

// OverlayPath returns the generated bridge overlay location for a project
// root. The file lives one level above the bridge runtime dir, next to the
// rest of `.dwe/` machine state (design D8).
func OverlayPath(baseDir string) string {
	return filepath.Join(baseDir, filepath.FromSlash(config.BridgeOverlayRelPath))
}

// ArchResolver resolves the linux GOARCH ("amd64"/"arm64") of the image
// backing one bridged service, identified by its docker container name.
// Errors are non-fatal — the caller falls back to the host architecture.
type ArchResolver func(containerName string) (string, error)

// CommandOutput is the injectable command seam for DockerArchResolver: run
// a binary with args and return its trimmed stdout.
type CommandOutput func(name string, args ...string) (string, error)

// execCommandOutput is the production CommandOutput (os/exec backed); exit
// errors surface their stderr, mirroring the other docker probes here.
func execCommandOutput(name string, args ...string) (string, error) {
	out, err := exec.Command(name, args...).Output() //nolint:gosec
	if err != nil {
		if exitErr, ok := errors.AsType[*exec.ExitError](err); ok && len(exitErr.Stderr) > 0 {
			return "", errors.New(strings.TrimSpace(string(exitErr.Stderr)))
		}
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// DockerArchResolver returns the production ArchResolver: container name →
// image ID (`docker container inspect`) → image Architecture (`docker image
// inspect`). The image is never pulled; a missing container (nothing
// deployed yet) or image surfaces as an error and the caller falls back to
// the host arch — the choice self-heals at the next regeneration once the
// container exists. run == nil uses the os/exec-backed runner.
func DockerArchResolver(run CommandOutput, dockerBin string) ArchResolver {
	if run == nil {
		run = execCommandOutput
	}
	return func(containerName string) (string, error) {
		imageID, err := run(dockerBin, "container", "inspect", "--format", "{{.Image}}", containerName)
		if err != nil {
			return "", err
		}
		return run(dockerBin, "image", "inspect", "--format", "{{.Architecture}}", imageID)
	}
}

// normalizeShimArch maps a reported architecture onto the shim GOARCH set.
func normalizeShimArch(arch string) (string, bool) {
	switch strings.TrimSpace(arch) {
	case "amd64", "x86_64":
		return "amd64", true
	case "arm64", "aarch64":
		return "arm64", true
	default:
		return "", false
	}
}

// hostShimArch is the fallback shim architecture: the host's own GOARCH —
// dev containers virtually always run the host's native arch (design D8);
// never hardcoded amd64.
func hostShimArch() string {
	if arch, ok := normalizeShimArch(runtime.GOARCH); ok {
		return arch
	}
	return runtime.GOARCH
}

// OverlaySpec is the pure input of RenderOverlay: everything the YAML needs,
// nothing config- or docker-shaped. BuildOverlaySpec assembles it from the
// loaded config; tests construct it directly for golden rendering.
type OverlaySpec struct {
	// BridgeDir is the absolute host path of `.dwe/bridge`. Mount sources
	// are absolute on purpose: a relative source in a compose file resolves
	// against the project directory (the FIRST -f file's directory), which
	// shifts with compose.base — and the overlay is regenerated machine
	// state, so baked absolute paths self-heal on the next compose-up.
	BridgeDir string
	// Project is the DWE_BRIDGE_PROJECT diagnostic identity (shim error
	// messages name the project the daemon is down for — design D10).
	Project string
	// Services in deploy order (config.DeployOrder — golden stability).
	Services []OverlayService
}

// OverlayService is one bridged service entry in the overlay.
type OverlayService struct {
	// Name is the compose service name (service.yml `container:`).
	Name string
	// ShimFile is the materialized shim binary name (shim-linux-<arch>),
	// chosen per image architecture at each regeneration.
	ShimFile string
	// ShimPath is the container path the shim is mounted at
	// (bridge.shim_path, default /usr/local/bin/dwe).
	ShimPath string
	// HostWorkspace / ContainerWorkspace drive shim cwd translation
	// (design D7): the absolute host hub dir and its in-container mount
	// point. Both empty when the service declares no dir / dir_internal
	// pair — the env pair is then omitted and untranslated cwds are
	// rejected by the daemon's containment check.
	HostWorkspace      string
	ContainerWorkspace string
	// UnreachableWarn sets DWE_BRIDGE_UNREACHABLE=warn: a dead daemon
	// becomes a warning + exit 0 instead of an error + exit 1 (design D10).
	UnreachableWarn bool
}

// BuildOverlaySpec assembles the overlay input for the current config:
// exactly the enabled AND bridge-enabled services, iterated via
// config.DeployOrder (never `range cfg.Services` — golden stability).
// baseDir is the absolute project root. Architecture resolution errors are
// non-fatal: the service falls back to the host arch with a warning through
// logf (nil discards diagnostics).
func BuildOverlaySpec(baseDir string, cfg *config.DweConfig, arch ArchResolver, logf func(format string, args ...any)) OverlaySpec {
	if logf == nil {
		logf = func(string, ...any) {}
	}
	spec := OverlaySpec{
		BridgeDir: DefaultBridgeDir(baseDir),
		Project:   cfg.Project.FullName(),
	}
	// Container names are derived as "<project>-<container>" while bypassing
	// compose, so the prefix MUST be the compose project name (docker.yml
	// project_name when set — config.ResolveComposeProjectName is the single
	// source of truth for that derivation), never Project.FullName().
	// spec.Project intentionally stays FullName: it is the DWE_BRIDGE_PROJECT
	// diagnostic identity, not a container prefix.
	composeProject, err := config.ResolveComposeProjectName(baseDir, cfg)
	if err != nil {
		composeProject = cfg.Project.FullName()
		logf("bridge: resolving compose project name: %v; using %q", err, composeProject)
	}
	for _, name := range config.DeployOrder(cfg, []string{"app", "tool", "infra"}) {
		svc := cfg.Services[name]
		if !svc.BridgeEnabled() {
			continue
		}
		if svc.Container == "" {
			// Unreachable after LoadConfig (container defaults to the folder
			// name) but literal-built configs can omit it — skip loudly
			// rather than emit a service entry compose cannot match.
			logf("bridge: service %q has no container name; skipping bridge injection", name)
			continue
		}
		entry := OverlayService{
			Name:            svc.Container,
			ShimFile:        shimassets.FileName(resolveShimArch(name, svc.Container, composeProject, arch, logf)),
			ShimPath:        svc.BridgeShimPath(),
			UnreachableWarn: svc.BridgeOnUnreachable() == config.BridgeOnUnreachableWarn,
		}
		if svc.Dir != "" && svc.DirInternal != "" {
			entry.HostWorkspace = filepath.Join(baseDir, svc.Dir)
			entry.ContainerWorkspace = svc.DirInternal
		}
		spec.Services = append(spec.Services, entry)
	}
	return spec
}

// resolveShimArch picks the shim architecture for one service: the image
// architecture reported by the resolver when it is one we ship a shim for,
// the host arch otherwise (with a warning — the wrong-arch window self-heals
// at the next regeneration). composeProject is the compose project name the
// container-name derivation prefixes with.
func resolveShimArch(name, containerTemplate, composeProject string, arch ArchResolver, logf func(format string, args ...any)) string {
	host := hostShimArch()
	if arch == nil {
		return host
	}
	containerName, err := shareddaemon.ResolveContainerName(composeProject, containerTemplate)
	if err == nil {
		var raw string
		raw, err = arch(containerName)
		if err == nil {
			if normalized, ok := normalizeShimArch(raw); ok {
				return normalized
			}
			logf("bridge: service %q image architecture %q has no shim; falling back to host arch %s", name, raw, host)
			return host
		}
		if isNoSuchContainer(err) {
			// Expected whenever the container does not exist yet (first
			// deploy, after reset) — the host-arch fallback is correct for
			// native images and re-resolves at the next start, so this is a
			// -v decision line, not a user-facing warning. The one case the
			// fallback gets wrong (emulated foreign-arch image → shim exec
			// format error in the container) is covered in the bridge
			// troubleshooting docs.
			trace.Decision(context.Background(),
				"bridge: service %q has no container yet; shim arch falls back to host %s (re-resolved at next start)",
				name, host)
			return host
		}
	}
	logf("bridge: resolving image architecture for service %q: %v; falling back to host arch %s", name, err, host)
	return host
}

// isNoSuchContainer matches the docker CLI's "No such container" inspect
// failure — the one expected resolver error (nothing deployed yet) among
// genuine diagnostics like an unreachable docker daemon.
func isNoSuchContainer(err error) bool {
	return err != nil && strings.Contains(strings.ToLower(err.Error()), "no such container")
}

// overlayDoc / overlayService / overlayMount mirror the compose schema
// subset the overlay emits. Field order is the YAML emission order.
type overlayDoc struct {
	Services orderedServices `yaml:"services"`
}

type overlayService struct {
	Volumes     []overlayMount    `yaml:"volumes"`
	Environment map[string]string `yaml:"environment"`
	ExtraHosts  []string          `yaml:"extra_hosts"`
}

type overlayMount struct {
	Type     string `yaml:"type"`
	Source   string `yaml:"source"`
	Target   string `yaml:"target"`
	ReadOnly bool   `yaml:"read_only"`
}

// namedService pairs a compose service name with its overlay body so the
// services mapping can preserve deploy order (yaml.v3 sorts plain maps).
type namedService struct {
	Name    string
	Service overlayService
}

type orderedServices []namedService

// MarshalYAML emits the services mapping in slice order.
func (s orderedServices) MarshalYAML() (any, error) {
	node := &yaml.Node{Kind: yaml.MappingNode}
	for _, entry := range s {
		key := &yaml.Node{Kind: yaml.ScalarNode, Value: entry.Name}
		value := &yaml.Node{}
		if err := value.Encode(entry.Service); err != nil {
			return nil, err
		}
		node.Content = append(node.Content, key, value)
	}
	return node, nil
}

// RenderOverlay renders the overlay YAML for a spec. Pure: spec in, bytes
// out — golden tests pin the output byte-for-byte.
func RenderOverlay(spec OverlaySpec) ([]byte, error) {
	doc := overlayDoc{Services: make(orderedServices, 0, len(spec.Services))}
	for _, svc := range spec.Services {
		// Env names are the D7 contract read by the shim
		// (bridgeclient.OptionsFromEnv) and stripped from forwarded env on
		// both sides (bridgeclient.StripEnv).
		env := map[string]string{
			"DWE_BRIDGE_DIR":     BridgeMountTarget,
			"DWE_BRIDGE_PROJECT": spec.Project,
		}
		if svc.HostWorkspace != "" && svc.ContainerWorkspace != "" {
			env["DWE_HOST_WORKSPACE"] = svc.HostWorkspace
			env["DWE_CONTAINER_WORKSPACE"] = svc.ContainerWorkspace
		}
		if svc.UnreachableWarn {
			env["DWE_BRIDGE_UNREACHABLE"] = config.BridgeOnUnreachableWarn
		}
		doc.Services = append(doc.Services, namedService{
			Name: svc.Name,
			Service: overlayService{
				Volumes: []overlayMount{
					{Type: "bind", Source: spec.BridgeDir, Target: BridgeMountTarget, ReadOnly: true},
					{Type: "bind", Source: filepath.Join(spec.BridgeDir, svc.ShimFile), Target: svc.ShimPath, ReadOnly: true},
				},
				Environment: env,
				ExtraHosts:  []string{extraHostGateway},
			},
		})
	}

	var buf bytes.Buffer
	buf.WriteString(overlayHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("bridge: rendering compose overlay: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("bridge: rendering compose overlay: %w", err)
	}
	return buf.Bytes(), nil
}

// RegenerateOverlay renders and atomically writes `.dwe/compose.bridge.yml`
// for the current config, or DELETES it when no enabled service has bridge
// enabled — a stale leftover would re-enter the -f chain and break compose
// for services that no longer define an image (design D8). It reports
// whether the file changed on disk. The overlay step of the bridge prepare
// hook calls this on EVERY compose-up command, even when bridge is fully
// off; shim materialization and daemon ensure are the steps that get
// skipped, never this one.
func RegenerateOverlay(baseDir string, cfg *config.DweConfig, arch ArchResolver, logf func(format string, args ...any)) (bool, error) {
	return regenerateOverlayFromSpec(baseDir, BuildOverlaySpec(baseDir, cfg, arch, logf))
}

// regenerateOverlayFromSpec is the spec-driven core of RegenerateOverlay,
// shared with Prepare (which also needs the spec for its skip decision and
// must not resolve architectures twice).
func regenerateOverlayFromSpec(baseDir string, spec OverlaySpec) (bool, error) {
	path := OverlayPath(baseDir)
	if len(spec.Services) == 0 {
		err := os.Remove(path)
		switch {
		case errors.Is(err, os.ErrNotExist):
			return false, nil
		case err != nil:
			return false, fmt.Errorf("bridge: removing compose overlay: %w", err)
		}
		return true, nil
	}

	data, err := RenderOverlay(spec)
	if err != nil {
		return false, err
	}
	// 0755 matches the other `.dwe` machine-state writers (promptcache,
	// generatedstore); only the bridge runtime subdir is 0700.
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("bridge: creating overlay dir: %w", err)
	}
	return writeFileIfChanged(path, data, overlayFilePerm)
}

// writeFileIfChanged replaces dst only when its content differs, via a
// same-dir temp file + rename — a half-written overlay must never be
// observable by a concurrently starting compose. Reports whether dst
// changed.
func writeFileIfChanged(dst string, data []byte, perm os.FileMode) (bool, error) {
	existing, err := os.ReadFile(dst)
	if err == nil && bytes.Equal(existing, data) {
		return false, nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("bridge: reading %s: %w", dst, err)
	}

	tmp, err := os.CreateTemp(filepath.Dir(dst), filepath.Base(dst)+".tmp-*")
	if err != nil {
		return false, fmt.Errorf("bridge: creating temp file: %w", err)
	}
	defer func() {
		_ = os.Remove(tmp.Name()) // no-op after successful rename
	}()
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return false, fmt.Errorf("bridge: writing %s: %w", dst, err)
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return false, fmt.Errorf("bridge: chmod %s: %w", dst, err)
	}
	if err := tmp.Close(); err != nil {
		return false, fmt.Errorf("bridge: closing temp file: %w", err)
	}
	if err := os.Rename(tmp.Name(), dst); err != nil {
		return false, fmt.Errorf("bridge: replacing %s: %w", dst, err)
	}
	return true, nil
}
