// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import starlightLinksValidator from 'starlight-links-validator';
import mermaidZoom from './src/integrations/mermaid-zoom.mjs';

// The sidebar is GENERATED by scripts/sync-docs.mjs (from each docs index.md's
// ordered TOC) and written to src/sidebar.generated.mjs — gitignored. The
// `prebuild`/`predev` npm scripts run the sync before Astro starts, so the file
// exists by the time this config loads. The try/catch keeps a bare `astro build`
// (without the sync) from hard-failing with an opaque import error.
let sidebar = [];
try {
  sidebar = (await import('./src/sidebar.generated.mjs')).default;
} catch (err) {
  // Only tolerate a genuinely-absent file (bare `astro build` without the sync).
  // A syntax/runtime error inside a generated sidebar must fail loudly rather
  // than silently degrade to an empty nav.
  if (err?.code !== 'ERR_MODULE_NOT_FOUND') throw err;
  console.warn('[astro.config] src/sidebar.generated.mjs missing — run `npm run sync` first. Falling back to empty sidebar.');
}

// https://astro.build/config
export default defineConfig({
  // Project GitHub Pages site: served under /dwe/. The sync script shares this
  // base when rewriting internal doc links (see BASE in scripts/sync-docs.mjs).
  site: 'https://semsemyonoff.github.io',
  base: '/dwe/',
  integrations: [
    // Transforms ```mermaid fences into rendered diagrams (the docs use ~43).
    // MUST precede starlight so its remark step claims the fences first.
    mermaid({ theme: 'neutral', autoTheme: true }),
    // Wraps each rendered diagram with pan/zoom/fit/fullscreen/export controls.
    mermaidZoom(),
    starlight({
      title: 'DWE',
      // The square DWE mark (the notification icon) shown beside the "DWE" title
      // in the header. Copied into src/assets/ by the sync (gitignored).
      logo: { src: './src/assets/dwe-logo.png', alt: 'DWE' },
      // Header title override appends the current version next to the logo.
      components: { SiteTitle: './src/components/SiteTitle.astro' },
      customCss: ['./src/styles/custom.css', './src/styles/mermaid-zoom.css'],
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/semsemyonoff/dwe',
        },
      ],
      // English is the root locale (content at src/content/docs/); Russian lives
      // under src/content/docs/ru/. Starlight auto-falls-back to English for any
      // page missing a Russian translation and renders the locale switcher.
      locales: {
        root: { label: 'English', lang: 'en' },
        ru: { label: 'Русский', lang: 'ru' },
      },
      sidebar,
      plugins: [
        // The correctness gate for the link rewrite: any internal link that does
        // not resolve to a built PAGE fails `astro build` (and thus CI).
        //
        // Hash (#anchor) validation is OFF: the canonical docs carry ~150
        // pre-existing anchor mismatches the mirror can't fix without editing
        // source — chiefly RU pages that link with English section anchors while
        // their headings are Russian (broken in the source docs too), plus a few
        // github-slugger edge cases (dots, double hyphens). Such links still land
        // on the correct page; they just don't scroll to the exact section. Page
        // existence stays strictly validated, so the link rewrite is still gated.
        starlightLinksValidator({ errorOnInvalidHashes: false }),
      ],
    }),
  ],
});
